/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador4_3.java
 *
 * Created on 27/10/2012, 10:05:35 PM
 */

package cif.gui.Criterio_4;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.objects.C_4_3_Object;
import cif.objects.Tala_Object;
import cif.utiles.utiles;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author casa, Raisel
 */
public class Indicador4_3 extends javax.swing.JPanel
{
    private String id;
    private String mun;
    private final String tablename;
    private String tag;
//    private final Object[][] result42;
    private JF_Principal princ;
    private int anno;
//    private int idtala;
    
    /** Creates new form Indicador4_3 */
    public Indicador4_3(Tala_Object []talas, String tag, String id, int anno, String tablename, JF_Principal princ, String mun)
    {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
        this.tag=tag;
        this.anno = anno;
        this.mun = mun;
//        this.idtala = idtala;
//        this.result42=result42;
        initComponents();

        for(int i=0; i<talas.length; i++)
         addTalaToList(talas[i]);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        modelSelectedTalas = new DefaultListModel();
        jLSelectedTalas = new javax.swing.JList(modelSelectedTalas);
        jScrollPane1 = new javax.swing.JScrollPane();
        modelTalas = new DefaultListModel();
        jLTalas = new javax.swing.JList(modelTalas);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBAsignar = new javax.swing.JButton();
        jLSupTot = new javax.swing.JLabel();
        jTFSupTotal = new javax.swing.JTextField();
        jLSuptecn = new javax.swing.JLabel();
        jTFSuptecn = new javax.swing.JTextField();
        jBAdd = new javax.swing.JButton();
        jBQuit = new javax.swing.JButton();
        jBQuitAll = new javax.swing.JButton();
        jBAddAll = new javax.swing.JButton();
        jBAceptar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jLSelectedTalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectedTalasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jLSelectedTalas);

        jLTalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTalasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLTalas);

        jLabel2.setText("Talas");

        jLabel3.setText("Datos");

        jBAsignar.setText("Asignar");
        jBAsignar.setEnabled(false);
        jBAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarActionPerformed(evt);
            }
        });

        jLSupTot.setText("Superficie total");
        jLSupTot.setEnabled(false);

        jTFSupTotal.setText("0.0");
        jTFSupTotal.setEnabled(false);
        jTFSupTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSupTotalKeyTyped(evt);
            }
        });

        jLSuptecn.setText("Superficie con técnicas adecuadas");
        jLSuptecn.setEnabled(false);

        jTFSuptecn.setText("0.0");
        jTFSuptecn.setEnabled(false);
        jTFSuptecn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSuptecnKeyTyped(evt);
            }
        });

        jBAdd.setText("-->");
        jBAdd.setEnabled(false);
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jBQuit.setText("<--");
        jBQuit.setEnabled(false);
        jBQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitActionPerformed(evt);
            }
        });

        jBQuitAll.setText("<<--");
        jBQuitAll.setEnabled(false);
        jBQuitAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitAllActionPerformed(evt);
            }
        });

        jBAddAll.setText("-->>");
        jBAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBQuitAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAddAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLSupTot)
                                    .addComponent(jTFSupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLSuptecn)
                                    .addComponent(jTFSuptecn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jBAsignar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel3))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jBAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBQuit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAddAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBQuitAll)
                        .addContainerGap(119, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLSupTot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFSupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSuptecn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFSuptecn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAsignar)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(575, Short.MAX_VALUE)
                .addComponent(jBAceptar)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsignarActionPerformed
        // TODO add your handling code here:
        //DBAccess.insertTalas(id,anno,idtalas,supfftot, supftecninad,tablename);
         int index = jLSelectedTalas.getSelectedIndex();
         C_4_3_Object object = (C_4_3_Object)jLSelectedTalas.getSelectedValue();
         String supTotalValue = jTFSupTotal.getText();
         String supTecnValue = jTFSuptecn.getText();
         double supTot = 0;
         double supTec = 0;

         if(!supTotalValue.trim().equals(""))
          supTot = Double.parseDouble(supTotalValue);

         if(!supTecnValue.trim().equals(""))
          supTec = Double.parseDouble(supTecnValue);

         if(supTec > supTot)
         {
             String mens = "La Superficie Total no debe ser menor que la Superficie con Técnicas Adecuadas!!!";
             JOptionPane.showMessageDialog(princ, mens, "Error", JOptionPane.ERROR_MESSAGE);
         }
         else
         {
             object.setSupTotal(supTot);
             object.setSupTecAdec(supTec);

             modelSelectedTalas.removeElement(object);
             modelSelectedTalas.add(index, object);

             SetFielValuesEnabled(false);
             jBQuit.setEnabled(false);
         }
    }//GEN-LAST:event_jBAsignarActionPerformed

    private void jTFSupTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSupTotalKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTFSupTotal.getText());
    }//GEN-LAST:event_jTFSupTotalKeyTyped

    private void jTFSuptecnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSuptecnKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTFSuptecn.getText());
    }//GEN-LAST:event_jTFSuptecnKeyTyped

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        // TODO add your handling code here:
        addSelectedTalaToList(jLTalas.getSelectedIndex());
        jTFSupTotal.requestFocusInWindow();
    }//GEN-LAST:event_jBAddActionPerformed

    private void jLTalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTalasMouseClicked
        // TODO add your handling code here:
        if(jLTalas.getSelectedIndex() >= 0)
         jBAdd.setEnabled(true);
    }//GEN-LAST:event_jLTalasMouseClicked

    private void jBAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddAllActionPerformed
        // TODO add your handling code here:
       
       while(modelTalas.getSize() > 0)
        addSelectedTalaToList(0);
    }//GEN-LAST:event_jBAddAllActionPerformed

    private void jLSelectedTalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectedTalasMouseClicked
        // TODO add your handling code here:
        if(jLSelectedTalas.getSelectedIndex() >= 0)
        {
         jBQuit.setEnabled(true);
         SetFielValuesEnabled(true);
         SetFieldValues((C_4_3_Object)jLSelectedTalas.getSelectedValue());
        }
    }//GEN-LAST:event_jLSelectedTalasMouseClicked

    private void jBQuitAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitAllActionPerformed
        // TODO add your handling code here:
       while(modelSelectedTalas.getSize() > 0)
        quitSelectedTalaFromList(0);

       SetFielValuesEnabled(false);
    }//GEN-LAST:event_jBQuitAllActionPerformed

    private void jBQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitActionPerformed
        // TODO add your handling code here:
        quitSelectedTalaFromList(jLSelectedTalas.getSelectedIndex());
        SetFielValuesEnabled(false);
    }//GEN-LAST:event_jBQuitActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:   
        int existe;
        try {
                if (tag.equals("insert"))
                {
                    String talasexisten = "";
                    ArrayList<C_4_3_Object> listaInsertar = new ArrayList<C_4_3_Object>();
                    for(int i=0; i<modelSelectedTalas.size(); i++)
                    {
                     C_4_3_Object tala = (C_4_3_Object)modelSelectedTalas.get(i);
                     existe = DBAccess.verificarPkey2("select id,anno,municipio ", tablename, " where id='"+id+"' and municipio='"+mun+"' " +
                                                      "and anno="+anno+" and id_talas="+tala.getTala().Id());
                     if(existe != 1)
                      listaInsertar.add(tala);
                     else
                      talasexisten += tala.getTala().Nombre()+",";
                    }

                    if(talasexisten.length() > 0)
                    {
                     talasexisten = talasexisten.substring(0, talasexisten.length()-1);
                     String mens = "Las siguientes talas ya existen en el sistema: "+"\n"+talasexisten+"\n";
                     mens += "¿Desea realizar la operación sin tenerlas en cuenta?";
                     Object[] options = {"Si", "No", "Cancelar"};
                     int res = JOptionPane.showOptionDialog(princ, mens, "Adevertencia!!!", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                               null, options, options[0]);

                     if(res == JOptionPane.OK_OPTION)
                      InsertarTALAS(listaInsertar);
                    }
                    else
                     InsertarTALAS(listaInsertar);
                    
//                    if(existe!=1)
//                    {
//                        DBAccess.insertTalas(id, princ.getSelectedYear(), idtala, supTot, supTec, tablename);
//                        restartFieldValues();
//                    }
//                    else
//                     JOptionPane.showConfirmDialog(this, "Ya existen datos para esta entidad en el año "+anno+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
                }
//                else
//                if (tag.equals("modify"))
//                {
//                    if(anno == princ.getSelectedYear())
//                    {
//                        DBAccess.updateTalas(id, princ.getSelectedYear(), anno, idtala, supTot, supTec, tablename);
//                        JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamnete.", "Confirmación!!!", JOptionPane.CLOSED_OPTION,JOptionPane.INFORMATION_MESSAGE);
//                        anno = princ.getSelectedYear();
//                    }
//                    else
//                    {
//                        existe=DBAccess.verificarPkey(id, princ.getSelectedYear(), tablename);
//                        if(existe!=1)
//                        {
//                            DBAccess.updateTalas(id, princ.getSelectedYear(), anno, idtala, supTot, supTec, tablename);
//                            JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamnete.", "Confirmación!!!", JOptionPane.CLOSED_OPTION,JOptionPane.INFORMATION_MESSAGE);
//                            anno = princ.getSelectedYear();
//                        }
//                        else
//                         JOptionPane.showConfirmDialog(this, "Ya existen datos para esta entidad en el año "+princ.getSelectedYear()+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
//                    }
//                }
            } catch (SQLException ex) {
                Logger.getLogger(Indicador4_2.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void addTalaToList(Tala_Object tala)
    {
     modelTalas.addElement(tala);
    }

    private void addSelectedTalaToList(int index)
    {
         Tala_Object tala = (Tala_Object)modelTalas.get(index);
//         String supTotalValue = jTFSupTotal.getText();
//         String supTecnValue = jTFSuptecn.getText();
//         double supTot = 0;
//         double supTec = 0;
//
//         if(!supTotalValue.trim().equals(""))
//          supTot = Double.parseDouble(supTotalValue);
//
//         if(!supTecnValue.trim().equals(""))
//          supTec = Double.parseDouble(supTecnValue);

         C_4_3_Object object = new C_4_3_Object("-1", tala, 0.0, 0.0);
         modelSelectedTalas.addElement(object);
         modelTalas.removeElement(tala);

         restartFieldValues();
         jBQuitAll.setEnabled(true);

         if(modelTalas.getSize() < 2)
          jBAddAll.setEnabled(false);

         jBAdd.setEnabled(false);
    }

    private void quitSelectedTalaFromList(int index)
    {
         C_4_3_Object object = (C_4_3_Object)modelSelectedTalas.get(index);

         modelSelectedTalas.removeElement(object);
         modelTalas.addElement(object.getTala());

         restartFieldValues();
         jBAddAll.setEnabled(true);

         if(modelSelectedTalas.getSize() < 2)
          jBQuitAll.setEnabled(false);

         jBQuit.setEnabled(false);
    }

    private void restartFieldValues()
    {
     jTFSupTotal.setText("0.0");
     jTFSuptecn.setText("0.0");
    }

    private void SetFieldValues(C_4_3_Object object)
    {   
     jTFSupTotal.setText(object.getSupTotal().toString());
     jTFSuptecn.setText(object.getSupTecAdec().toString());
    }

    private void SetFielValuesEnabled(boolean flag)
    {
     restartFieldValues();
     jLSupTot.setEnabled(flag);
     jLSuptecn.setEnabled(flag);
     jTFSupTotal.setEnabled(flag);
     jTFSuptecn.setEnabled(flag);
     jBAsignar.setEnabled(flag);
    }

    private void InsertarTALAS(ArrayList<C_4_3_Object> listaInsertar) throws SQLException
    {
     for(int i=0; i<listaInsertar.size(); i++)
     {
      C_4_3_Object tala = listaInsertar.get(i);
      DBAccess.insertTalas(id, princ.getSelectedYear(), tala.getTala().Id(), tala.getSupTotal(), tala.getSupTecAdec(), tablename);
     }

     while(modelSelectedTalas.getSize() > 0)
     {
      C_4_3_Object object = (C_4_3_Object)modelSelectedTalas.get(0);
      modelSelectedTalas.removeElement(object);
     }
     
     SetFielValuesEnabled(false);
     JOptionPane.showMessageDialog(null, "Elementos insertados correctamente");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBAddAll;
    private javax.swing.JButton jBAsignar;
    private javax.swing.JButton jBQuit;
    private javax.swing.JButton jBQuitAll;
    private javax.swing.JList jLSelectedTalas;
    private javax.swing.JLabel jLSupTot;
    private javax.swing.JLabel jLSuptecn;
    private javax.swing.JList jLTalas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFSupTotal;
    private javax.swing.JTextField jTFSuptecn;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel modelTalas;
    private DefaultListModel modelSelectedTalas;
}