/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador4_3.java
 *
 * Created on 27/10/2012, 10:05:35 PM
 */

package cif.gui.Criterio_4;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.objects.C_4_3_Object;
import cif.objects.Tala_Object;
import cif.utiles.utiles;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador4_3_Modify extends javax.swing.JPanel {

    private String id;
    private String mun;
    private final String tablename;
//    private String tag;
//    private final Object[][] result42;
    private JF_Principal princ;
    private int anno;
//    private int idtala;
    
    /** Creates new form Indicador4_3 */
    public Indicador4_3_Modify(C_4_3_Object []talas, String id, int anno, String tablename, JF_Principal princ, String mun)
    {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
//        this.tag=tag;
        this.anno = anno;
        this.mun = mun;
//        this.idtala = idtala;
//        this.result42=result42;
        initComponents();

        if(talas != null)
        {
            for(int i=0; i<talas.length; i++)
             addTalaToList(talas[i]);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        modelSelectedTalas = new DefaultListModel();
        jLSelectedTalas = new javax.swing.JList(modelSelectedTalas);
        jLabel3 = new javax.swing.JLabel();
        jBAsignar = new javax.swing.JButton();
        jLSupTot = new javax.swing.JLabel();
        jTFSupTotal = new javax.swing.JTextField();
        jLSuptecn = new javax.swing.JLabel();
        jTFSuptecn = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jLSelectedTalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSelectedTalasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jLSelectedTalas);

        jLabel3.setText("Datos");

        jBAsignar.setText("Asignar");
        jBAsignar.setEnabled(false);
        jBAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarActionPerformed(evt);
            }
        });

        jLSupTot.setText("Superficie total");
        jLSupTot.setEnabled(false);

        jTFSupTotal.setText("0.0");
        jTFSupTotal.setEnabled(false);
        jTFSupTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSupTotalKeyTyped(evt);
            }
        });

        jLSuptecn.setText("Superficie con técnicas adecuadas");
        jLSuptecn.setEnabled(false);

        jTFSuptecn.setText("0.0");
        jTFSuptecn.setEnabled(false);
        jTFSuptecn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSuptecnKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jBAsignar))
                            .addComponent(jLSupTot)
                            .addComponent(jTFSupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSuptecn)
                            .addComponent(jTFSuptecn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLSupTot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLSuptecn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSuptecn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAsignar)))
                .addContainerGap())
        );

        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(jBAceptar)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsignarActionPerformed
        // TODO add your handling code here:
        //DBAccess.insertTalas(id,anno,idtalas,supfftot, supftecninad,tablename);
         int index = jLSelectedTalas.getSelectedIndex();
         C_4_3_Object object = (C_4_3_Object)jLSelectedTalas.getSelectedValue();
         String supTotalValue = jTFSupTotal.getText();
         String supTecnValue = jTFSuptecn.getText();
         double supTot = 0;
         double supTec = 0;

         if(!supTotalValue.trim().equals(""))
          supTot = Double.parseDouble(supTotalValue);

         if(!supTecnValue.trim().equals(""))
          supTec = Double.parseDouble(supTecnValue);

         if(supTec > supTot)
         {
             String mens = "La Superficie Total no debe ser menor que la Superficie con Técnicas Adecuadas!!!";
             JOptionPane.showMessageDialog(princ, mens, "Error", JOptionPane.ERROR_MESSAGE);
         }
         else
         {
             object.setSupTotal(supTot);
             object.setSupTecAdec(supTec);

             modelSelectedTalas.removeElement(object);
             modelSelectedTalas.add(index, object);

             SetFielValuesEnabled(false);
         }
    }//GEN-LAST:event_jBAsignarActionPerformed

    private void jTFSupTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSupTotalKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTFSupTotal.getText());
    }//GEN-LAST:event_jTFSupTotalKeyTyped

    private void jTFSuptecnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSuptecnKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTFSuptecn.getText());
    }//GEN-LAST:event_jTFSuptecnKeyTyped

    private void jLSelectedTalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSelectedTalasMouseClicked
        // TODO add your handling code here:
        if(jLSelectedTalas.getSelectedIndex() >= 0)
        {
         SetFielValuesEnabled(true);
         SetFieldValues((C_4_3_Object)jLSelectedTalas.getSelectedValue());
        }
    }//GEN-LAST:event_jLSelectedTalasMouseClicked

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:   
    try {
                    int existe = 0;
                    String talasexisten = "";
                    ArrayList<C_4_3_Object> listaAct = new ArrayList<C_4_3_Object>();
                    for(int i=0; i<modelSelectedTalas.size(); i++)
                    {
                     C_4_3_Object tala = (C_4_3_Object)modelSelectedTalas.get(i);

                     if(anno != princ.getSelectedYear())
                      existe = DBAccess.verificarPkey2("select id,anno,municipio ", tablename, " where id='"+id+"' and municipio='"+mun+"' " +
                                                      "and anno="+princ.getSelectedYear()+" and id_talas="+tala.getTala().Id());
                     if(existe != 1)
                      listaAct.add(tala);
                     else
                      talasexisten += tala.getTala().Nombre()+",";

                     existe = 0;
                    }

                    if(talasexisten.length() > 0)
                    {
                     talasexisten = talasexisten.substring(0, talasexisten.length()-1);
                     String mens = "Las siguientes talas ya existen en el sistema para el periodo "+princ.getSelectedYear()+": "+"\n"+talasexisten+"\n";
                     mens += "Los datos de estas no se actualizarán!!!";
                     JOptionPane.showMessageDialog(null, mens);
                    }

                    if(listaAct.size() > 0)
                     ActualizarTalas(listaAct);
            
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al actualizar elementos");
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void restartFieldValues()
    {
     jTFSupTotal.setText("0.0");
     jTFSuptecn.setText("0.0");
    }

    private void SetFielValuesEnabled(boolean flag)
    {
     restartFieldValues();
     jLSupTot.setEnabled(flag);
     jLSuptecn.setEnabled(flag);
     jTFSupTotal.setEnabled(flag);
     jTFSuptecn.setEnabled(flag);
     jBAsignar.setEnabled(flag);
    }

    private void ActualizarTalas(ArrayList<C_4_3_Object> listaAct) throws SQLException
    {
     for(int i=0; i<listaAct.size(); i++)
     {
      C_4_3_Object tala = (C_4_3_Object)listaAct.get(i);
      DBAccess.updateTalas(id, princ.getSelectedYear(), anno, tala.getTala().Id(), tala.getSupTotal(), tala.getSupTecAdec(), tablename);
     }

     SetFielValuesEnabled(false);
     JOptionPane.showMessageDialog(null, "Elementos actualizados correctamente");
    }

    private void addTalaToList(C_4_3_Object tala)
    {
     modelSelectedTalas.addElement(tala);
    }

    private void SetFieldValues(C_4_3_Object object)
    {
     jTFSupTotal.setText(object.getSupTotal().toString());
     jTFSuptecn.setText(object.getSupTecAdec().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAsignar;
    private javax.swing.JList jLSelectedTalas;
    private javax.swing.JLabel jLSupTot;
    private javax.swing.JLabel jLSuptecn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFSupTotal;
    private javax.swing.JTextField jTFSuptecn;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel modelSelectedTalas;
}