/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador2_1.java
 *
 * Created on 26/10/2012, 12:06:18 AM
 */

package cif.gui.Criterio_2;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.manage.Manage;
import cif.manage.User;
import cif.utiles.Adv_ComboBox;
import cif.utiles.utiles;
import java.awt.Container;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author casa
 */
public class Indicador2_1 extends javax.swing.JPanel {
    private final String id;
    private final String tablename;
    private final Object[][] result21;
    private final String tag;
    private boolean existeInc;
    JF_Principal princ;
    private int anno;

    /** Creates new form Indicador2_1 */
    public Indicador2_1(String id,JF_Principal princ,String tablename,String tag,Object[][] result21) {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
        this.tag=tag;
        this.result21=result21;
        anno=princ.getSelectedYear();
        //initComponents();     
        init();
        ActiveFields();
        if (tag.equals("modify")) {
           manageInc();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_DistRec = new javax.swing.JTextField();
        jTextField_CantInc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_SupAfeTot = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_PerdDir = new javax.swing.JTextField();
        jTextField_Hectp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_PerdInd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton_Aceptar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos generales Incendios"));

        jLabel2.setText("Cantidad de incendios(u):");

        jLabel3.setText("Distancia recorrida(ha):");

        jTextField_DistRec.setText("0.0");
        jTextField_DistRec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DistRecKeyTyped(evt);
            }
        });

        jTextField_CantInc.setText("0");
        jTextField_CantInc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CantIncKeyTyped(evt);
            }
        });

        jLabel4.setText("Superficie afectada total(ha):");

        jTextField_SupAfeTot.setText("0.0");
        jTextField_SupAfeTot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SupAfeTotKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_DistRec)
                            .addComponent(jTextField_CantInc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SupAfeTot)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_CantInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_DistRec, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_SupAfeTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Especies"));

        jLabel5.setText("Hectáreas perdidas(ha):");

        jLabel6.setText("Pérdidas directas($):");

        jTextField_PerdDir.setText("0.0");
        jTextField_PerdDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PerdDirKeyTyped(evt);
            }
        });

        jTextField_Hectp.setText("0.0");
        jTextField_Hectp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_HectpKeyTyped(evt);
            }
        });

        jLabel7.setText("Pérdidas indirectas($):");

        jTextField_PerdInd.setText("0.0");
        jTextField_PerdInd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PerdIndKeyTyped(evt);
            }
        });

        jLabel8.setText("Especie:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_PerdInd)
                            .addComponent(jTextField_PerdDir)
                            .addComponent(jTextField_Hectp, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Hectp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_PerdDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_PerdInd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jButton_Aceptar.setText("Aceptar");
        jButton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton_Aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void init() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_DistRec = new javax.swing.JTextField();
        jTextField_CantInc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_SupAfeTot = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_PerdDir = new javax.swing.JTextField();
        jTextField_Hectp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_PerdInd = new javax.swing.JTextField();
        jComboBoxEspecie = new Adv_ComboBox();
        fillCombobox();
        jLabel8 = new javax.swing.JLabel();
        jButton_Aceptar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos generales"));

        jLabel2.setText("Cantidad de incendios(u):");

        jLabel3.setText("Distancia recorrida(ha):");

        jTextField_DistRec.setText("0.0");
        jTextField_DistRec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DistRecKeyTyped(evt);
            }
        });

        jTextField_CantInc.setText("0");
        jTextField_CantInc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CantIncKeyTyped(evt);
            }
        });

        jLabel4.setText("Superficie afectada total(ha):");

        jTextField_SupAfeTot.setText("0.0");
        jTextField_SupAfeTot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SupAfeTotKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_DistRec)
                            .addComponent(jTextField_CantInc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SupAfeTot)))
                .addContainerGap(2, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_CantInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_DistRec, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_SupAfeTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Especies"));

        jLabel5.setText("Hectáreas perdidas(ha):");

        jLabel6.setText("Pérdidas directas($):");

        jTextField_PerdDir.setText("0.0");
        jTextField_PerdDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PerdDirKeyTyped(evt);
            }
        });


  /*  princ.addChangeListenerToJSpinner(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStateChanged(evt);
            }
        });*/
                
        jTextField_Hectp.setText("0.0");
        jTextField_Hectp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_HectpKeyTyped(evt);
            }
        });

        jLabel7.setText("Pérdidas indirectas($):");

        jTextField_PerdInd.setText("0.0");
        jTextField_PerdInd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PerdIndKeyTyped(evt);
            }
        });

        jLabel8.setText("Especie:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_PerdInd)
                            .addComponent(jTextField_PerdDir)
                            .addComponent(jTextField_Hectp, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Hectp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_PerdDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_PerdInd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jComboBoxEspecie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEspecieItemStateChanged(evt);
            }
        });

        jButton_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png")));
        jButton_Aceptar.setText("Aceptar");
        jButton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Aceptar)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, 0, 255, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }


    private void jButton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarActionPerformed

        // TODO add your handling code here:
        Integer cant,idespecie;
        Double distrec,superftot,perddir, perdind, haperd;
        cant=java.lang.Integer.parseInt(jTextField_CantInc.getText());
        distrec=java.lang.Double.parseDouble(jTextField_DistRec.getText());
        superftot=java.lang.Double.parseDouble(jTextField_SupAfeTot.getText());
        idespecie=java.lang.Integer.parseInt(jComboBoxEspecie.getSelectedValue().toString());
        perddir=java.lang.Double.parseDouble(jTextField_PerdDir.getText());
        String namespecie=jComboBoxEspecie.getSelectedItem().toString();
        perdind=java.lang.Double.parseDouble(jTextField_PerdInd.getText());
        haperd=java.lang.Double.parseDouble(jTextField_Hectp.getText());
        int existe;
        try {
            if(cant!=0)
                {
                    if(tag.equals("insert"))
                    {
                        Manage manager = Manage.getInstance();
                        User user = manager.getUser();
                        String select="select id, especie, anno, perd_direc, perd_indir, hectar_perd, municipio";
                        String where="where id='"+id+"' and municipio='"+user.getMunicipio()+"' and  especie='"+idespecie+"' and  anno="+princ.getSelectedYear()+"";
                        existe=DBAccess.verificarPkey2(select, tablename, where);
                        if(existe!=1)
                        {
                            if (existeInc==false)
                            {
                                DBAccess.insertInc(id, princ.getSelectedYear(), cant, distrec, superftot, gettabnameINC());
                                DBAccess.insertIncEsp(id, princ.getSelectedYear(), idespecie, perddir, perdind, haperd, tablename);
                                fillCombobox();
                                jTextField_PerdDir.setText("0.0");
                                jTextField_PerdInd.setText("0.0");
                                jTextField_Hectp.setText("0.0");
                                ActiveFields();
                            } else {
                                DBAccess.insertIncEsp(id, princ.getSelectedYear(), idespecie, perddir, perdind, haperd, tablename);
                                jTextField_PerdDir.setText("0.0");
                                jTextField_PerdInd.setText("0.0");
                                jTextField_Hectp.setText("0.0");
                            }
                        }
                        else
                            {
                                JOptionPane.showConfirmDialog(this, "Ya existen datos para esta entidad en el año "+princ.getSelectedYear()+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
                            }
                    }
                    else if (tag.equals("modify"))
                    {
                        /*if(cant==0)
                        {
                           int option = JOptionPane.showConfirmDialog(this, "Advertencia!!!", "La cantidad de incendios insertada es 0, lo que implica n/ eliminar las especies afectadas por los incendios en la Entidad."
                           + "n/ ¿Desea realizar dicha operación?", JOptionPane.YES_NO_OPTION);
                           if (option == JOptionPane.OK_OPTION)
                           {
                               DBAccess.delete(id, tablename);
                               DBAccess.delete(id, gettabnameINC());
                       }
                        }*/
                       /* else{*/
                        if(anno==princ.getSelectedYear())
                        {
                            DBAccess.updateInc(id, princ.getSelectedYear(),anno, cant, distrec, superftot, gettabnameINC());
                            DBAccess.updateIncEsp(id, princ.getSelectedYear(),anno, idespecie, perddir, perdind, haperd, tablename);
                            //fillCombobox();
                            JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamente.", "Confirmación!!!", JOptionPane.CLOSED_OPTION,JOptionPane.INFORMATION_MESSAGE);
                            anno=princ.getSelectedYear();
                        //}*/
                        }
                        else
                        {
                             existe=DBAccess.verificarPkey(id, princ.getSelectedYear(), gettabnameINC());
                             if(existe!=1)
                             {
                                Manage manager = Manage.getInstance();
                                User user = manager.getUser();
                                String select="select id, especie, anno, perd_direc, perd_indir, hectar_perd, municipio";
                                String where="where id='"+id+"' and municipio='"+user.getMunicipio()+"' and  especie='"+idespecie+"' and  anno="+princ.getSelectedYear()+"";
                                existe=DBAccess.verificarPkey2(select, tablename, where);
                                 //existe=DBAccess.verificarPkey(id, princ.getSelectedYear(), tablename);
                                 if(existe!=1)
                                 {
                                    DBAccess.updateInc(id, princ.getSelectedYear(),anno, cant, distrec, superftot, gettabnameINC());
                                    DBAccess.updateIncEsp(id, princ.getSelectedYear(),anno, idespecie, perddir, perdind, haperd, tablename);
                                    DBAccess.UpdateEspc(id,princ.getSelectedYear(),anno, tablename);
                                    //fillCombobox();
                                    JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamnete.", "Confirmación!!!", JOptionPane.CLOSED_OPTION,JOptionPane.INFORMATION_MESSAGE);
                                    anno=princ.getSelectedYear();
                                 }
                                 else
                                 {
                                      JOptionPane.showConfirmDialog(this, "Ya existen datos de la Especie:"+namespecie+" \n\r para esta Entidad en el año "+princ.getSelectedYear()+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
                                 }
                             }
                             else
                             {
                                 JOptionPane.showConfirmDialog(this, "Ya existen Datos Generales de Incendios \n\r para esta Entidad en el año "+princ.getSelectedYear()+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
                             }
                        }
                    }
            }
            else
            {
                JOptionPane.showConfirmDialog(this, "La cantidad de incendios no puede ser 0.", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
                    Logger.getLogger(Indicador2_1.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton_AceptarActionPerformed

    private void jTextField_CantIncKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CantIncKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumberInteger(evt);
    }//GEN-LAST:event_jTextField_CantIncKeyTyped

    private void jTextField_DistRecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DistRecKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_DistRec.getText());
    }//GEN-LAST:event_jTextField_DistRecKeyTyped

    private void jTextField_SupAfeTotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SupAfeTotKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_SupAfeTot.getText());
    }//GEN-LAST:event_jTextField_SupAfeTotKeyTyped

    private void jTextField_HectpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HectpKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_Hectp.getText());
    }//GEN-LAST:event_jTextField_HectpKeyTyped

    private void jTextField_PerdDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PerdDirKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_PerdDir.getText());
    }//GEN-LAST:event_jTextField_PerdDirKeyTyped

    private void jTextField_PerdIndKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PerdIndKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_PerdInd.getText());
    }//GEN-LAST:event_jTextField_PerdIndKeyTyped

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if(evt.getAncestorParent() instanceof Container)
        {
            jTextField_CantInc.requestFocusInWindow();
        }
    }//GEN-LAST:event_formAncestorAdded

    private void jComboBoxEspecieItemStateChanged(java.awt.event.ItemEvent evt) {
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.DESELECTED)//si se escogio un dato del combo q no es el q sale por defecto y no te repite la 0operación 2veces
             return;
        if(tag.equals("modify"))
        {
            SelectedCombox();
        }
    }

    private void jSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {
        ActiveFields();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Aceptar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField_CantInc;
    public javax.swing.JTextField jTextField_DistRec;
    public javax.swing.JTextField jTextField_Hectp;
    public javax.swing.JTextField jTextField_PerdDir;
    public javax.swing.JTextField jTextField_PerdInd;
    public javax.swing.JTextField jTextField_SupAfeTot;
    // End of variables declaration//GEN-END:variables
    public Adv_ComboBox jComboBoxEspecie;

    private void fillCombobox() {
            jComboBoxEspecie.removeAllItems();
            Object datos[][];
        try {
                datos = DBAccess.getComboboxEspecie(tablename,tag,id,princ.getSelectedYear());
                for (int i = 0; i < datos.length; i++) {
                    jComboBoxEspecie.addItem(datos[i][0].toString(), datos[i][1].toString());
                }
        } catch (SQLException ex) {
            Logger.getLogger(Indicador2_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ActiveFields() {
        try {
            
            Object[][] array21 = DBAccess.selectInc(id, princ.getSelectedYear(), gettabnameINC());
            if(array21.length>0 && tag.equals("insert"))
            {
                System.out.println("1-");
                jTextField_CantInc.setText(array21[0][0].toString());
                jTextField_DistRec.setText(array21[0][1].toString());
                jTextField_SupAfeTot.setText(array21[0][2].toString());
                jTextField_CantInc.setEditable(false);
                jTextField_DistRec.setEditable(false);
                jTextField_SupAfeTot.setEditable(false);
                existeInc=true;
            }
            else if(array21.length>0 && tag.equals("modify"))
            {
                System.out.println("2");
                jTextField_CantInc.setText(array21[0][0].toString());
                jTextField_DistRec.setText(array21[0][1].toString());
                jTextField_SupAfeTot.setText(array21[0][2].toString());
                jTextField_CantInc.setEditable(true);
                jTextField_DistRec.setEditable(true);
                jTextField_SupAfeTot.setEditable(true);
                existeInc=false;
                SelectedCombox();
            }
            else if(array21.length==0 && tag.equals("modify"))
            {
                JOptionPane.showConfirmDialog(this, "No existen incendios en el año "+princ.getSelectedYear()+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
                jTextField_CantInc.setText("0");
                jTextField_DistRec.setText("0.0");
                jTextField_SupAfeTot.setText("0.0");
                jTextField_PerdDir.setText("0.0");
                jTextField_PerdInd.setText("0.0");
                jTextField_Hectp.setText("0.0");
                SelectedCombox();
            }
            else if(array21.length==0 && tag.equals("insert"))
            {
                jTextField_CantInc.setText("0");
                jTextField_DistRec.setText("0.0");
                jTextField_SupAfeTot.setText("0.0");
                jTextField_CantInc.setEditable(true);
                jTextField_DistRec.setEditable(true);
                jTextField_SupAfeTot.setEditable(true);
                existeInc=false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Indicador2_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String gettabnameINC()
    {
        String nametabinc = null;
        if (tablename.equals("c2_1_ap_incespecie")) {
            nametabinc="c2_1_ap_bosquesafectinc";
        } else if (tablename.equals("c2_1_otros_incespecie")){
            nametabinc="c2_1_otros_bosquesafectinc";
        }else{
            nametabinc="c2_1_us_bosquesafectinc";
        }
        return nametabinc;
    }

    private void manageInc() {
         try {
                this.jComboBoxEspecie.setSelectedValue(result21[0][0].toString());
                this.jTextField_PerdDir.setText(result21[0][1].toString());
                this.jTextField_PerdInd.setText(result21[0][2].toString());
                this.jTextField_Hectp.setText(result21[0][3].toString());
                //-----------------------------**--------------------------//
                Object[][] arrayInc = DBAccess.selectInc(id, princ.getSelectedYear(), gettabnameINC());
                this.jTextField_CantInc.setText(arrayInc[0][0].toString());
                this.jTextField_DistRec.setText(arrayInc[0][1].toString());
                this.jTextField_SupAfeTot.setText(arrayInc[0][2].toString());
            } catch (SQLException ex) {
                Logger.getLogger(Indicador2_1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    private void SelectedCombox()
    {
        try {
                int idesp = java.lang.Integer.parseInt(jComboBoxEspecie.getSelectedValue().toString());
                String columns="perd_direc,perd_indir,hectar_perd";
                Integer ano = null;
                if(tag.equals("insert"))
                {
                    ano=princ.getSelectedYear();
                }
                else if(tag.equals("modify"))
                {
                    ano=anno;
                }

                Object[][] comboxEspc = DBAccess.selectComboxcEsp(id, ano, tablename, idesp,columns);
                if(comboxEspc.length>0)
                {
                    for (int i = 0; i < comboxEspc.length; i++) {
                        jTextField_PerdDir.setText(comboxEspc[0][0].toString());
                        jTextField_PerdInd.setText(comboxEspc[0][1].toString());
                        jTextField_Hectp.setText(comboxEspc[0][2].toString());
                        System.out.println("---------1-------");
                    }
                }
                else
                {
                    jTextField_PerdDir.setText("0.0");
                    jTextField_PerdInd.setText("0.0");
                    jTextField_Hectp.setText("0.0");
                    System.out.println("---------2-------");
                }
                 
            } catch (SQLException ex) {
                Logger.getLogger(Indicador2_1.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

     private void UpdateEspc()
    {

    }
}
