/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginDialog1.java
 *
 * Created on 19/10/2012, 09:11:57 AM
 */

package cif.gui;

import cif.manage.Manage;
import cif.manage.User;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RootPaneContainer;

/**
 *
 * @author Pedro
 */
public class LoginDialog extends javax.swing.JDialog {

    /** Creates new form LoginDialog1 */
    JF_Principal principal;
    public LoginDialog(JF_Principal princ_frame)
    {
        principal = princ_frame;
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        Point p = new Point((dim.width/2)-(d.width/2),(dim.height/2)-(d.height/2));
        setLocation(p);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        acept = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        invalid_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autenticación");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Contraseña:");

        acept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        acept.setText("Aceptar");
        acept.setSelected(true);
        acept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptMouseClicked(evt);
            }
        });
        acept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aceptKeyTyped(evt);
            }
        });

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-cancel.png"))); // NOI18N
        cancel.setText("Cancelar");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cancelKeyTyped(evt);
            }
        });

        invalid_label.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(acept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(invalid_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(invalid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(acept))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        if(evt.getButton() == evt.BUTTON1)
    	{
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_cancelMouseClicked

    private void aceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptMouseClicked
        try
        {
            if(evt.getButton() == evt.BUTTON1)
            {
               if(tryToLogin())
               {
                    dispose();
               }
               return;
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(
                    this,
                    "</html>"+e.getMessage()+"</html>",//Mensaje
                    "Error",//titulo
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptMouseClicked

    private void aceptKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aceptKeyTyped
         try
        {
            if(evt.getKeyChar() == evt.VK_ENTER)
            {
               if(tryToLogin())
               {
                    dispose();
               }
               return;
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(
                    this,
                    "</html>"+e.getMessage()+"</html>",//Mensaje
                    "Error",//titulo
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptKeyTyped

    private void cancelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelKeyTyped
        if(evt.getKeyChar() == evt.VK_ENTER)
    	{
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_cancelKeyTyped

    private boolean tryToLogin() throws SQLException
    {
        String user, passw;
        user = login.getText();
        passw = new String(password.getPassword());
        Manage manage = Manage.getInstance();
        User usuario = manage.initUser(user, passw);
        if(usuario == null)
        {
            invalid_label.setText("Usuario o contraseña incorrectos");
            return false;
        }
        setVisible(false);
        principal.ValidateComponents();
        return true;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDialog(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acept;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel invalid_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

}
