/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AP_Panel.java
 *
 * Created on 18/01/2013, 11:16:18 AM
 */

package cif.gui.entidades;

import cif.adminstration.bd.DBQueries;
import cif.adminstration.utiles.Utils;
import cif.bd.BDUtilities;
import cif.utiles.Adv_ComboBox;
import java.awt.Color;
import java.awt.Container;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class AP_Panel extends javax.swing.JPanel {

    /** Creates new form AP_Panel */
    private static final int INSERT = 0;
    private static final int UPDATE = 1;
    private int action;
    private String actual_id; //esta variable tiene el id de la US que se esté modificando
    public AP_Panel() {
        init();
        FillCombo(BDUtilities.getProvincias(), prov_field);
        FillCombo(BDUtilities.getSignificacion(), signif_field);
        action = INSERT;
    }

    public AP_Panel(String nombre, String tenente, String signif, String municipio,String plan_manejo)
    {
        init();
        FillCombo(BDUtilities.getProvincias(), prov_field);
        FillCombo(BDUtilities.getSignificacion(), signif_field);
        action = UPDATE;
        name_field.setText(nombre);
        tenente_field.setText(tenente);
        signif_field.setSelectedItem(signif);
        actual_id = BDUtilities.getAPId(nombre, tenente,signif, municipio);
        String provincia = BDUtilities.getProvFromIdAP(actual_id);
        prov_field.setSelectedValue(provincia);
  //      FillCombo(BDUtilities.getMunicipios(provincia), munic_field);
        munic_field.setSelectedItem(municipio);
        if(plan_manejo.equals("Si"))
        {
            plan_manejo_field.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_name = new javax.swing.JLabel();
        label_prov = new javax.swing.JLabel();
        label_munic = new javax.swing.JLabel();
        label_tenente = new javax.swing.JLabel();
        label_signif = new javax.swing.JLabel();
        plan_manejo_field = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        acept = new javax.swing.JButton();
        tenente_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        label_name.setText("*Nombre:");

        label_prov.setText("Provincia:");

        label_munic.setText("*Municipio:");

        label_tenente.setText("*Tenente:");

        label_signif.setText("*Significación:");

        plan_manejo_field.setText("Plan de Manejo");

        jLabel6.setText("(*)Obligatorio");

        cancel.setText("Cancelar");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        acept.setText("Aceptar");
        acept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plan_manejo_field)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(acept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_prov, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addGap(275, 275, 275))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_munic, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_tenente, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenente_field, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_signif, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addGap(261, 261, 261))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(label_prov)
                .addGap(17, 17, 17)
                .addComponent(label_munic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenente_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tenente))
                .addGap(18, 18, 18)
                .addComponent(label_signif, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(plan_manejo_field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acept)
                        .addComponent(cancel))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
        {
            setVisible(false);
        }
    }//GEN-LAST:event_cancelMouseClicked

    private void aceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptMouseClicked
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
        {
            Insert();
        }
    }//GEN-LAST:event_aceptMouseClicked

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if(evt.getAncestorParent() instanceof Container)
        {
            name_field.requestFocusInWindow();
        }
    }//GEN-LAST:event_formAncestorAdded

    private void init() {

        label_name = new javax.swing.JLabel();
        label_prov = new javax.swing.JLabel();
        label_munic = new javax.swing.JLabel();
        label_tenente = new javax.swing.JLabel();
        label_signif = new javax.swing.JLabel();
        plan_manejo_field = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        acept = new javax.swing.JButton();
        tenente_field = new javax.swing.JTextField();
        signif_field = new Adv_ComboBox();
        munic_field = new Adv_ComboBox();
        prov_field = new Adv_ComboBox();
        name_field = new javax.swing.JTextField();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setFocusCycleRoot(true);
        label_name.setText("*Nombre:");

        label_prov.setText("Provincia:");

        label_munic.setText("*Municipio:");

        label_tenente.setText("*Tenente:");

        label_signif.setText("*Significación:");

        plan_manejo_field.setText("Plan de Manejo");

        jLabel6.setText("(*)Obligatorio");

        acept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aceptKeyTyped(evt);
            }
        });

        name_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        tenente_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tenenteKeyTyped(evt);
            }
        });

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-cancel.png")));
        cancel.setText("Cancelar");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cancelKeyTyped(evt);
            }
        });

        acept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png")));
        acept.setText("Aceptar");
        acept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aceptMouseClicked(evt);
            }
        });

        prov_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provActionPerformed();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(plan_manejo_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_prov, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(prov_field, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_munic, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(munic_field, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_tenente, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenente_field, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_signif, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signif_field, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(label_prov))
                    .addComponent(prov_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(label_munic))
                    .addComponent(munic_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenente_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tenente))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_signif, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signif_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(plan_manejo_field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acept)
                        .addComponent(cancel))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }

    private void aceptKeyTyped(java.awt.event.KeyEvent evt) {
        if(evt.getKeyChar() == evt.VK_ENTER)
        {
            Insert();
        }
    }

    private void cancelKeyTyped(java.awt.event.KeyEvent evt) {
        if(evt.getKeyChar() == evt.VK_ENTER)
        {
            setVisible(false);
        }
    }

    private void nameKeyTyped(java.awt.event.KeyEvent evt)
    {
        if(!Character.isLetter(evt.getKeyChar()) && evt.getKeyChar() != ' ')
        {
            evt.consume();
        }
    }

    private void tenenteKeyTyped(java.awt.event.KeyEvent evt)
    {
        if(evt.getKeyChar() == '*' || evt.getKeyChar() == '/' || evt.getKeyChar() == '\\' || evt.getKeyChar() == '+'
                || evt.getKeyChar() == '&' || evt.getKeyChar() == '%' || evt.getKeyChar() == '$' || evt.getKeyChar() == '@'
                || evt.getKeyChar() == '>' || evt.getKeyChar() == '<' || evt.getKeyChar() == '!' || evt.getKeyChar() == '#'
                || evt.getKeyChar() == '?' || evt.getKeyChar() == ':' || evt.getKeyChar() == '=')
        {
            evt.consume();
        }
    }

    private void FillCombo(Object[][] types, Adv_ComboBox combo)
    {
        combo.addItem(-1, "<Seleccionar>");
        for(int i=0; i<types.length; i++)
        {
            Object[] aux = types[i];
            combo.addItem(aux[0], aux[1]);
        }
    }

    private void provActionPerformed()
    {
        if(prov_field.getSelectedValue() != null && !prov_field.getSelectedValue().toString().equals("-1"))
        {
            ResetCombo(munic_field, true);
            FillCombo(BDUtilities.getMunicipios(prov_field.getSelectedValue().toString()), munic_field);
            munic_field.setEnabled(true);
        }
        else
        {
            ResetCombo(munic_field, true);
            munic_field.setEnabled(false);
        }
    }

    private void Insert()
    {
        String nombre,municipio,provincia;
        boolean error = false;
        nombre = name_field.getText().toUpperCase();
        if(nombre.isEmpty())
        {
            error = true;
            label_name.setForeground(Color.red);
        }
        else
        {
            label_name.setForeground(Color.black);
        }
        provincia = prov_field.getSelectedValue().toString();
        municipio = null;
        if(munic_field.getSelectedValue() != null)
        {
            municipio = munic_field.getSelectedValue().toString();
        }
        if(municipio == null || municipio.equals("-1"))
        {
            error = true;
            label_munic.setForeground(Color.red);
        }
        else
        {
            label_munic.setForeground(Color.black);
        }
        String tenente = tenente_field.getText().toUpperCase();
        if(tenente.isEmpty())
        {
            error = true;
            label_tenente.setForeground(Color.red);
        }
        else
        {
            label_tenente.setForeground(Color.black);
        }
        String signif = signif_field.getSelectedValue().toString();
        if(signif == null || signif.equals("-1"))
        {
            error = true;
            label_signif.setForeground(Color.red);
        }
        else
        {
            label_signif.setForeground(Color.black);
        }
        int plan = 0;
        if(plan_manejo_field.isSelected())
        {
            plan = 1;
        }
        if(error)
        {
            JOptionPane.showInternalMessageDialog(Utils.getParentFrame(this).getContentPane(),"Existen campos en blanco que son de caracter obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
            error = false;
            return;
        }
        else
        {
            try
            {
                if(action == INSERT)
                {
                
                    if(!DBQueries.ExistAP(nombre, municipio, tenente,signif))
                    {
                        DBQueries.InsertAP(nombre, tenente, municipio, provincia,signif,plan);
                        ResetWindow();
                    }
                    else
                    {
                        JOptionPane.showInternalMessageDialog(Utils.getParentFrame(this).getContentPane(),"Esta Área Protegida ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                
                }
                else
                {
                    DBQueries.UpdateAP(nombre, tenente, municipio,signif,plan, actual_id);
                    JOptionPane.showInternalMessageDialog(Utils.getParentFrame(this).getContentPane(),"Los datos se modificaron satisfactoriamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showInternalMessageDialog(Utils.getParentFrame(this).getContentPane(),"Ocurrió el siguiente error \n\r" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }

    private void ResetWindow()
    {
        name_field.setText("");
        tenente_field.setText("");
        ResetCombo(prov_field, false);
        ResetCombo(signif_field, false);
        ResetCombo(munic_field, true);
        plan_manejo_field.setSelected(false);
    }

    private void ResetCombo(JComboBox combo,boolean erase)
    {
        if(erase)
        {
            combo.removeAllItems();
            return;
        }
        combo.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acept;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_munic;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_prov;
    private javax.swing.JLabel label_signif;
    private javax.swing.JLabel label_tenente;
    private javax.swing.JTextField name_field;
    private javax.swing.JCheckBox plan_manejo_field;
    private javax.swing.JTextField tenente_field;
    // End of variables declaration//GEN-END:variables
    private Adv_ComboBox prov_field;
    private Adv_ComboBox signif_field;
    private Adv_ComboBox munic_field;
}
