/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador5_5.java
 *
 * Created on 27/10/2012, 11:35:57 PM
 */

package cif.gui.Criterio_5;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.objects.C_5_4_Object;
import cif.objects.C_5_5_Object;
import cif.objects.TipoServicio_Object;
import cif.utiles.utiles;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casa, Raisel
 */
public class Indicador5_4_Modify extends javax.swing.JPanel
{
    private String id;
    private String mun;
    private final String tablename;
    private String tag;
    private JF_Principal princ;
    private int anno;

    /** Creates new form Indicador5_4 */
    public Indicador5_4_Modify(C_5_4_Object []servicios, String id, int anno, String tablename, JF_Principal princ, String mun)
    {
        this.id = id;
        this.princ = princ;
        this.tablename = tablename;
        this.tag = tag;
        this.anno = anno;
        this.mun = mun;

        initComponents();

        if(servicios != null)
        {
            for(int i=0; i<servicios.length; i++)
             addServicioToList(servicios[i]);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        modelSeleccionados = new DefaultListModel();
        jLSeleccionados = new javax.swing.JList(modelSeleccionados);
        jLabel3 = new javax.swing.JLabel();
        jBAsignar = new javax.swing.JButton();
        jLCant = new javax.swing.JLabel();
        jTFCant = new javax.swing.JTextField();
        jLPlanManej = new javax.swing.JLabel();
        jTFPlanManej = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jLSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSeleccionadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jLSeleccionados);

        jLabel3.setText("Datos");

        jBAsignar.setText("Asignar");
        jBAsignar.setEnabled(false);
        jBAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarActionPerformed(evt);
            }
        });

        jLCant.setText("Cantidad");
        jLCant.setEnabled(false);

        jTFCant.setEnabled(false);
        jTFCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantKeyTyped(evt);
            }
        });

        jLPlanManej.setText("Planes de manejo");
        jLPlanManej.setEnabled(false);

        jTFPlanManej.setEnabled(false);
        jTFPlanManej.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPlanManejKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLCant))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLPlanManej))
                            .addComponent(jTFCant, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jBAsignar))
                            .addComponent(jTFPlanManej, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(216, 216, 216)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLCant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLPlanManej)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPlanManej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAsignar)))
                .addContainerGap())
        );

        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(jBAceptar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsignarActionPerformed
        // TODO add your handling code here:
         int index = jLSeleccionados.getSelectedIndex();
         C_5_4_Object object = (C_5_4_Object)jLSeleccionados.getSelectedValue();
         String cantValue = jTFCant.getText();
         String planmanejValue = jTFPlanManej.getText();
         int cant = 0;
         int planmanej = 0;

         if(!cantValue.trim().equals(""))
          cant = Integer.parseInt(cantValue);

         if(!planmanejValue.trim().equals(""))
          planmanej = Integer.parseInt(planmanejValue);

         object.setCantidad(cant);
         object.setPlan_manejo(planmanej);

         modelSeleccionados.removeElement(object);
         modelSeleccionados.add(index, object);

         SetFielValuesEnabled(false);
    }//GEN-LAST:event_jBAsignarActionPerformed

    private void jTFCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumberInteger(evt);
    }//GEN-LAST:event_jTFCantKeyTyped

    private void jTFPlanManejKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPlanManejKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumberInteger(evt);
    }//GEN-LAST:event_jTFPlanManejKeyTyped

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:
      try {
                    int existe = 0;
                    String existen = "";
                    ArrayList<C_5_4_Object> listaAct = new ArrayList<C_5_4_Object>();
                    for(int i=0; i<modelSeleccionados.size(); i++)
                    {
                     C_5_4_Object serv = (C_5_4_Object)modelSeleccionados.get(i);

                     if(anno != princ.getSelectedYear())
                      existe = DBAccess.verificarPkey2("select id,anno,municipio ", tablename, " where id='"+id+"' and municipio='"+mun+"' " +
                                                      "and anno="+princ.getSelectedYear()+" and id_serv="+serv.getTipoServicio().Id());
                     if(existe != 1)
                      listaAct.add(serv);
                     else
                      existen += serv.getTipoServicio().Nombre()+",";

                     existe = 0;
                    }

                    if(existen.length() > 0)
                    {
                     existen = existen.substring(0, existen.length()-1);
                     String mens = "Los siguientes servicios ya existen en el sistema para el periodo "+princ.getSelectedYear()+": "+"\n"+existen+"\n";
                     mens += "Los datos de estos no se actualizarán!!!";
                     JOptionPane.showMessageDialog(null, mens);
                    }

                    if(listaAct.size() > 0)
                     ActualizarServicios(listaAct);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al actualizar elementos");
        }
}//GEN-LAST:event_jBAceptarActionPerformed

    private void jLSeleccionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSeleccionadosMouseClicked
        // TODO add your handling code here:
        if(jLSeleccionados.getSelectedIndex() >= 0)
        {
         SetFielValuesEnabled(true);
         SetFieldValues((C_5_4_Object)jLSeleccionados.getSelectedValue());
        }
    }//GEN-LAST:event_jLSeleccionadosMouseClicked

    private void restartFieldValues()
    {
     jTFCant.setText("0");
     jTFPlanManej.setText("0");
    }

    private void SetFielValuesEnabled(boolean flag)
    {
     restartFieldValues();
     jLCant.setEnabled(flag);
     jLPlanManej.setEnabled(flag);
     jTFCant.setEnabled(flag);
     jTFPlanManej.setEnabled(flag);
     jBAsignar.setEnabled(flag);
    }   

    private void addServicioToList(C_5_4_Object serv)
    {
     modelSeleccionados.addElement(serv);
    }

    private void SetFieldValues(C_5_4_Object object)
    {
     jTFCant.setText(object.getCantidad().toString());
     jTFPlanManej.setText(object.getPlan_manejo().toString());
    }

    private void ActualizarServicios(ArrayList<C_5_4_Object> listaAct) throws SQLException
    {
     for(int i=0; i<listaAct.size(); i++)
     {
      C_5_4_Object serv = (C_5_4_Object)listaAct.get(i);
      DBAccess.updateServicios(id, princ.getSelectedYear(), anno, serv.getTipoServicio().Id(), serv.getCantidad(), serv.getPlan_manejo(), tablename);
     }

     SetFielValuesEnabled(false);
     JOptionPane.showMessageDialog(null, "Elementos actualizados correctamente");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAsignar;
    private javax.swing.JLabel jLCant;
    private javax.swing.JLabel jLPlanManej;
    private javax.swing.JList jLSeleccionados;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFCant;
    private javax.swing.JTextField jTFPlanManej;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel modelSeleccionados;
}
