/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador3_1_3.java
 *
 * Created on 27/10/2012, 07:56:17 PM
 */

package cif.gui.Criterio_3;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.manage.Manage;
import cif.manage.User;
import cif.utiles.ProgramaProtec;
import cif.utiles.utiles;
import java.awt.Container;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador3_1_3 extends javax.swing.JPanel {
private final String id;
    private final JF_Principal princ;
    private final String tablename;
    private final Object[][] result313;
    private Object[][] idprog;
    ProgramaProtec objPP[];
    ArrayList<ProgramaProtec> adatos;
    /** Creates new form Indicador3_1_3 */
    public Indicador3_1_3(String id,JF_Principal princ,String tablename,String tag,Object[][] result313) {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
        this.result313=result313;
        initComponents();
        //******//******************//************//
        adatos=new  ArrayList<ProgramaProtec>();
        DefaultListModel mdpp=new DefaultListModel();
        jList_Datos.setModel(mdpp);
        createProgama();
        ShowProgama();
        jList_Prog.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonDer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Datos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Prog = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonIzq = new javax.swing.JButton();
        jButtonAllIzq = new javax.swing.JButton();
        jButtonAllDer = new javax.swing.JButton();
        jButtonAsignar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jButtonDer.setText("-->");
        jButtonDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDerActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jList_Datos);

        jScrollPane1.setViewportView(jList_Prog);

        jLabel2.setText("Programas de Protección");

        jLabel3.setText("Datos");

        jButtonIzq.setText("<--");
        jButtonIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzqActionPerformed(evt);
            }
        });

        jButtonAllIzq.setText("<<--");
        jButtonAllIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllIzqActionPerformed(evt);
            }
        });

        jButtonAllDer.setText("-->>");
        jButtonAllDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllDerActionPerformed(evt);
            }
        });

        jButtonAsignar.setText("Asignar");
        jButtonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarActionPerformed(evt);
            }
        });

        jLabel4.setText("Superficie(ha):");

        jTextField1.setText("0.0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAllDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDer, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jButtonAllIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIzq, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAsignar)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtonDer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAllDer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIzq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAllIzq)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAsignar)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
        );

        jButtonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jButtonOk.setText("Aceptar");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarActionPerformed
        if (!jList_Datos.isSelectionEmpty())
        {
            Double value=java.lang.Double.parseDouble(jTextField1.getText());
            adatos.get(jList_Datos.getSelectedIndex()).setValor(value);
           ((DefaultListModel)jList_Datos.getModel()).setElementAt(adatos.get(jList_Datos.getSelectedIndex()).getNombre()+" --- Prog de Protec: "+value ,jList_Datos.getSelectedIndex());
            jTextField1.setText("0.0");
        }
        else
        {
           JOptionPane.showConfirmDialog(this, "Debe seleccionar un Programa \n\r de protección en la casilla: Datos.", "Atención!!!", JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAsignarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButtonDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDerActionPerformed
        // TODO add your handling code here:
        if(jList_Prog.isSelectionEmpty())
        {
            return;
        }
        Derecha(jList_Prog.getSelectedIndex());
        jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_jButtonDerActionPerformed

    private void jButtonIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzqActionPerformed
        // TODO add your handling code here:
        if (jList_Datos.isSelectionEmpty())
        {
            return;
        }
        Izquierda(jList_Datos.getSelectedIndex());
    }//GEN-LAST:event_jButtonIzqActionPerformed

    private void jButtonAllIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllIzqActionPerformed
        // TODO add your handling code here:
        while (jList_Datos.getModel().getSize()>0) {
        Izquierda(0);
        }
    }//GEN-LAST:event_jButtonAllIzqActionPerformed

    private void jButtonAllDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllDerActionPerformed
        // TODO add your handling code here:
        while (jList_Prog.getModel().getSize()>0) {
         jList_Prog.setSelectedIndex(0);
         Derecha(0);
        }
    }//GEN-LAST:event_jButtonAllDerActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        int existe;
        Manage manager = Manage.getInstance();
        User user = manager.getUser();
        ArrayList errors = new ArrayList();
        ArrayList<String> namePP=new ArrayList<String>();
                for (int i = 0; i < adatos.size(); i++)
                {
                try {
                    String select = "select id, id_ejecprgm, anno,  municipio";
                    String where = "where id='" + id + "' and municipio='" + user.getMunicipio() + "' and  id_ejecprgm='" + adatos.get(i).getId() + "' and  anno=" + princ.getSelectedYear() + " ";
                    existe = DBAccess.verificarPkey2(select, tablename, where);
                    if (existe != 1) {
                        DBAccess.insertEjecProgProtec(id, princ.getSelectedYear(), java.lang.Integer.parseInt(adatos.get(i).getId()),adatos.get(i).getValor(), tablename);
                    } else {
                        errors.add(new Integer(i));
                        namePP.add(DBAccess.getnameIdentidad(adatos.get(i).getId(), "c3_1_3_ejecprogprotec"));
                        continue;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_2.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
        if (errors.size() > 0)
            {
                String msg ="";
                String mfsg="";
                String saltoLine = null;
                String ap="\n\rpara esta entidad en el año "+princ.getSelectedYear()+".";
                String msgff="Ya existe(n) el(los) Programa(s) de Protección: \n\r";
                for (Integer i =0; i < errors.size(); i++)
                {
                   Double multp4=Double.valueOf(i.doubleValue()/4);
                    Integer multp4_I=(int) Math.floor(multp4);//integer
                    Double retornomultp4=multp4-multp4_I;//se resta el decim-integ
                    if(i!=0 && (retornomultp4).equals(0.0))//si el resultado es entero
                    {
                        if(i!=errors.size()-1)
                        {
                            saltoLine="\n\r";
                        }
                        else if(i==errors.size()-1)
                        {
                            saltoLine="";
                        }
                    }
                    else
                    {
                       if(i!=errors.size()-1)
                        {
                            saltoLine="-";
                        }
                        else if(i==errors.size()-1)
                        {
                            saltoLine="";
                        }
                    }
                    msg = msg+namePP.get(i)+saltoLine;
                }
                    mfsg = msgff+msg+ap;
                    JOptionPane.showConfirmDialog(this, mfsg, "Error!!!", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
            adatos.clear();
            ((DefaultListModel)jList_Datos.getModel()).removeAllElements();
            ((DefaultListModel)jList_Prog.getModel()).removeAllElements();
            ShowProgama();
            jTextField1.setText("0.0");
    }//GEN-LAST:event_jButtonOkActionPerformed


    private void createProgama()
    {
        try {
            String where="where active=true";
            idprog = DBAccess.selectNomenclator("c3_1_3_ejecprogprotec",where);
            objPP=new ProgramaProtec[idprog.length];
            for (int i = 0; i < idprog.length; i++) {
            objPP[i]=new ProgramaProtec(idprog[i][0].toString(), idprog[i][1].toString(),0.0);
            System.out.println(objPP[i].getNombre());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Indicador3_1_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ShowProgama()
    {
        DefaultListModel modeloPP = new DefaultListModel();
        for (int j = 0; j < objPP.length; j++) {
                modeloPP.addElement(objPP[j]);
            }
         jList_Prog.setModel(modeloPP);
    }

     private void Derecha(int index)
    {
        DefaultListModel dmPP=(DefaultListModel) jList_Prog.getModel();
        ProgramaProtec elemPP=(ProgramaProtec) dmPP.get(index);
        adatos.add(elemPP);
        ((DefaultListModel)jList_Datos.getModel()).addElement(elemPP.getNombre()+" --- Prog de Protec: 0.0");
        dmPP.remove(index);
        jList_Datos.setSelectedIndex(0);
        if (jList_Prog.getModel().getSize()>0) {
           jList_Prog.setSelectedIndex(0);
        }
    }

    private void Izquierda(int index)
    {
        DefaultListModel dfmEE=(DefaultListModel) jList_Prog.getModel();
        dfmEE.addElement(adatos.get(index));
        adatos.remove(index);
        ((DefaultListModel) jList_Datos.getModel()).remove(index);
        if (jList_Datos.getModel().getSize()>0) {
           jList_Datos.setSelectedIndex(0);
        }
        jList_Prog.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAllDer;
    private javax.swing.JButton jButtonAllIzq;
    private javax.swing.JButton jButtonAsignar;
    private javax.swing.JButton jButtonDer;
    private javax.swing.JButton jButtonIzq;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList_Datos;
    private javax.swing.JList jList_Prog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
