/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador3_1_4.java
 *
 * Created on 27/10/2012, 08:15:00 PM
 */

package cif.gui.Criterio_3;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.manage.Manage;
import cif.manage.User;
import cif.utiles.ProgramaEduc;
import cif.utiles.utiles;
import java.awt.Container;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador3_1_4_Mod extends javax.swing.JPanel {
    private final String id;
    private final JF_Principal princ;
    private final String tablename;
    private final Object[][] result314;
    private Object[][] idact;
    ProgramaEduc objAct[];
    ArrayList<ProgramaEduc> adatos;
    private int anno;

    /** Creates new form Indicador3_1_4 */
    public Indicador3_1_4_Mod(String id,JF_Principal princ,String tablename,Object[][] result314) {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
        this.result314=result314;
        initComponents();
        anno=princ.getSelectedYear();
        adatos=new  ArrayList<ProgramaEduc>();
        DefaultListModel mdact=new DefaultListModel();
        jListDatos.setModel(mdact);
        createActv();
        ShowActv();
        jListActiv.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDatos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListActiv = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAsignar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jScrollPane3.setViewportView(jListDatos);

        jListActiv.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListActivValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListActiv);

        jLabel2.setText("Actividades");

        jLabel3.setText("Datos");

        jButtonAsignar.setText("Asignar");
        jButtonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de Actividades");

        jTextField1.setText("0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel5.setText("Cantidad de Participantes");

        jTextField2.setText("0");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAsignar)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(156, 156, 156)
                .addComponent(jLabel3)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAsignar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jButtonOK.setText("Aceptar");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonOK)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarActionPerformed
        // TODO add your handling code here:
       String name=jTextField1.getText();
       String name1=jTextField2.getText();
        if (!jListDatos.isSelectionEmpty())
        {
            ((DefaultListModel) jListDatos.getModel()).setElementAt(objAct[jListActiv.getSelectedIndex()].getNombre()+ " --- Cant Actv: " + name+" --- Particip: " + name1, jListDatos.getSelectedIndex());
            objAct[jListActiv.getSelectedIndex()].setValor1(java.lang.Integer.parseInt(name));
            objAct[jListActiv.getSelectedIndex()].setValor2(java.lang.Integer.parseInt(name1));
        }
        else
        {
           JOptionPane.showConfirmDialog(this, "Debe seleccionar un Programa \n\r de Educación en la casilla: Datos.", "Atención!!!", JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAsignarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        utiles.SoloNumberInteger(evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        utiles.SoloNumberInteger(evt);
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        int existe;
        Manage manager = Manage.getInstance();
        User user = manager.getUser();
        ArrayList errors = new ArrayList();
        ArrayList<String> namePP=new ArrayList<String>();
        if(anno==princ.getSelectedYear())
        {
            for (int i = 0; i < objAct.length; i++)
            {
                try {
                    DBAccess.updateProgEducExt(id, princ.getSelectedYear(), anno, objAct[i].getId(), objAct[i].getValor1(),objAct[i].getValor2(), tablename);
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_4_Mod.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            for (int j = 0; j < objAct.length; j++)
            {
                try {
                    String select = "select id, id_ejeceduc, anno, municipio";
                    String where = "where id='" + id + "' and municipio='" + user.getMunicipio() + "' and  id_ejeceduc='" + objAct[j].getId() + "' and  anno=" + princ.getSelectedYear() + "";
                    existe = DBAccess.verificarPkey2(select, tablename, where);
                    if (existe == 1) {
                        errors.add(new Integer(j));
                        namePP.add(objAct[j].getNombre());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_3_Mod.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (errors.size() > 0)
            {
            String msg ="";
            String mfsg="";
            String saltoLine = null;
            String ap="\n\rpara esta entidad en el año "+princ.getSelectedYear()+".";
            String msgff="Ya existe(n) el(los) Programa(s) de Educación y Extención: \n\r";
            for (Integer i =0; i < errors.size(); i++)
            {
               Double multp4=Double.valueOf(i.doubleValue()/4);
                Integer multp4_I=(int) Math.floor(multp4);//integer
                Double retornomultp4=multp4-multp4_I;//se resta el decim-integ
                if(i!=0 && (retornomultp4).equals(0.0))//si el resultado es entero
                {
                 if(i!=errors.size()-1)
                  {
                      saltoLine="\n\r";
                  }
                  else if(i==errors.size()-1)
                  {
                      saltoLine="";
                  }
                }
                else
                {
                   if(i!=errors.size()-1)
                   {
                      saltoLine="-";
                   }
                  else if(i==errors.size()-1)
                  {
                      saltoLine="";
                  }
                }
                msg = msg+namePP.get(i)+saltoLine;
            }
                mfsg = msgff+msg+ap;
                JOptionPane.showConfirmDialog(this, mfsg, "Error!!!", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        else
        {
            try {
                for (int j = 0; j < objAct.length; j++)
                {
                    DBAccess.updateProgEducExt(id, princ.getSelectedYear(), anno, objAct[j].getId(), objAct[j].getValor1(), objAct[j].getValor2(), tablename);
                }
                anno = princ.getSelectedYear();
                JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamente.", "Confirmación!!!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                jTextField1.setText("0");
                jTextField2.setText("0");
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_3_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jListActivValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListActivValueChanged
        // TODO add your handling code here:
        DefaultListModel modelodatos = new DefaultListModel();
        Integer value = objAct[jListActiv.getSelectedIndex()].getValor1();
        Integer value1 = objAct[jListActiv.getSelectedIndex()].getValor2();
        modelodatos.addElement(objAct[jListActiv.getSelectedIndex()].getNombre() + " --- Cant Activ: " + value+" --- Cant Activ: " + value1);
        jListDatos.setModel(modelodatos);
        jListDatos.setSelectedIndex(0);
        jTextField1.setText(value.toString());
        jTextField2.setText(value1.toString());
    }//GEN-LAST:event_jListActivValueChanged

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if(evt.getAncestorParent() instanceof Container)
        {
            jTextField1.requestFocusInWindow();
        }
    }//GEN-LAST:event_formAncestorAdded

    private void createActv()
    {
      objAct=new ProgramaEduc[result314.length];
            for (int i = 0; i <result314.length; i++) {
            try {
                objAct[i] = new ProgramaEduc(result314[i][0].toString(), DBAccess.getnameIdentidad(result314[i][0].toString(), "c3_1_4_progeducext"), java.lang.Integer.parseInt(result314[i][1].toString()),java.lang.Integer.parseInt(result314[i][2].toString()));
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_4_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }

    private void ShowActv()
    {
        DefaultListModel modeloAct = new DefaultListModel();
        for (int j = 0; j < objAct.length; j++) {
            try {
                modeloAct.addElement(DBAccess.getnameIdentidad(result314[j][0].toString(), "c3_1_4_progeducext"));
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_4_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
         jListActiv.setModel(modeloAct);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListActiv;
    private javax.swing.JList jListDatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
