/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador3_1_1.java
 *
 * Created on 27/10/2012, 06:24:24 PM
 */

package cif.gui.Criterio_3;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.manage.Manage;
import cif.manage.User;
import cif.utiles.FormForestal;
import cif.utiles.utiles;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador3_1_1 extends javax.swing.JPanel {
    private final String tablename;
    JF_Principal princ;
    private  int anno;
    private final Object[][] result311,idsap;
    private Object[][] idFF;
    FormForestal[] objFF;
    Hashtable<String,ArrayList<FormForestal>> datos,FF;
    //ashtable<String,DefaultListModel> FF;
    /** Creates new form Indicador3_1_1 */
    public Indicador3_1_1(Object[][] idsap,JF_Principal princ,String tablename,Object[][] result311) {
        this.idsap=idsap;
        this.princ=princ;
        this.tablename=tablename;
        this.result311=result311;
        initComponents();
        DefaultListModel mdff=new DefaultListModel();
        jList_Datos.setModel(mdff);
        //----------------//*------------------
        datos= new Hashtable<String, ArrayList<FormForestal>>();
        FF= new Hashtable<String,ArrayList<FormForestal>>();
        jList_AreaProt.setListData(getAPnames());
        jList_AreaProt.setSelectedIndex(0);        
        createFF();
        ShowFF();
        jList_FormFores.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_flechaDer = new javax.swing.JButton();
        jTextField_Sup = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Datos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_FormFores = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_AreaProt = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_flechaIzq = new javax.swing.JButton();
        jButton_flechaAllIzq = new javax.swing.JButton();
        jButton_flechaAllDer = new javax.swing.JButton();
        jButton_Ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jButton_flechaDer.setText("-->");
        jButton_flechaDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_flechaDerActionPerformed(evt);
            }
        });

        jTextField_Sup.setText("0.0");
        jTextField_Sup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SupKeyTyped(evt);
            }
        });

        jList_Datos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList_Datos);

        jList_FormFores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList_FormFores);

        jList_AreaProt.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_AreaProt.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_AreaProtValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList_AreaProt);

        jLabel1.setText("Áreas Protegidas");

        jLabel2.setText("Formaciones Forestales");

        jLabel3.setText("Datos");

        jButton_flechaIzq.setText("<--");
        jButton_flechaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_flechaIzqActionPerformed(evt);
            }
        });

        jButton_flechaAllIzq.setText("<<--");
        jButton_flechaAllIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_flechaAllIzqActionPerformed(evt);
            }
        });

        jButton_flechaAllDer.setText("-->>");
        jButton_flechaAllDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_flechaAllDerActionPerformed(evt);
            }
        });

        jButton_Ok.setText("Asignar");
        jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkActionPerformed(evt);
            }
        });

        jLabel4.setText("Superficie(ha)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_flechaAllIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_flechaIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_flechaDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_flechaAllDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton_Ok))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Sup, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel3)))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jButton_Ok))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton_flechaDer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_flechaAllDer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_flechaIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_flechaAllIzq)))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkActionPerformed
       Double superf=Double.parseDouble(jTextField_Sup.getText());
        if (!jList_Datos.isSelectionEmpty())
        {
           datos.get(idsap[jList_AreaProt.getSelectedIndex()][0].toString()).get(jList_Datos.getSelectedIndex()).setValor(superf);
           ((DefaultListModel)jList_Datos.getModel()).setElementAt(datos.get(idsap[jList_AreaProt.getSelectedIndex()][0].toString()).get(jList_Datos.getSelectedIndex()).getNombre()+" --- Superficie: "+superf, jList_Datos.getSelectedIndex());
            jTextField_Sup.setText("0.0");
        }
        else
        {
           JOptionPane.showConfirmDialog(this, "Debe seleccionar una Formación \n\r Forestal en la casilla: Datos.", "Atención!!!", JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_OkActionPerformed

    private void jTextField_SupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SupKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_Sup.getText());
    }//GEN-LAST:event_jTextField_SupKeyTyped

    private void jButton_flechaDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_flechaDerActionPerformed
        if(jList_FormFores.isSelectionEmpty())
        {
            return;
        }
        Derecha(jList_AreaProt.getSelectedIndex(), jList_FormFores.getSelectedIndex());
        jTextField_Sup.requestFocusInWindow();
    }//GEN-LAST:event_jButton_flechaDerActionPerformed

    private void jList_AreaProtValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_AreaProtValueChanged
    DefaultListModel dfmFF=new DefaultListModel();
    DefaultListModel dfmDatos=new DefaultListModel();
    //DefaultListModel dfmDatos=new DefaultListModel();
    ArrayList<FormForestal> arFFHT;
    arFFHT=FF.get(idsap[jList_AreaProt.getSelectedIndex()][0].toString());
    if (arFFHT!=null)
     {
         for (int i = 0; i < arFFHT.size(); i++) {
            dfmFF.addElement(arFFHT.get(i).getNombre());
     }
    jList_FormFores.setModel(dfmFF);
    ArrayList<FormForestal> ardatosHT;
    ardatosHT=datos.get(idsap[jList_AreaProt.getSelectedIndex()][0].toString());
    if(ardatosHT!=null)
    {
      for (int i = 0; i < ardatosHT.size(); i++)
        {
            dfmDatos.addElement(ardatosHT.get(i).getNombre()+" --- Superficie: "+ardatosHT.get(i).getValor());
        }      
    }
    jList_Datos.setModel(dfmDatos);
    }
    }//GEN-LAST:event_jList_AreaProtValueChanged

    private void jButton_flechaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_flechaIzqActionPerformed
        // TODO add your handling code here:        
        if (jList_Datos.isSelectionEmpty())
        {
            return;
        }
        Izquierda(jList_AreaProt.getSelectedIndex(),jList_Datos.getSelectedIndex());
    }//GEN-LAST:event_jButton_flechaIzqActionPerformed

    private void jButton_flechaAllDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_flechaAllDerActionPerformed
        // TODO add your handling code here:
        while (jList_FormFores.getModel().getSize()>0){
           Derecha(jList_AreaProt.getSelectedIndex(), 0);
        }
    }//GEN-LAST:event_jButton_flechaAllDerActionPerformed

    private void jButton_flechaAllIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_flechaAllIzqActionPerformed
        // TODO add your handling code here:
        while (jList_Datos.getModel().getSize()>0) {
        Izquierda(jList_AreaProt.getSelectedIndex(),0);
        }
    }//GEN-LAST:event_jButton_flechaAllIzqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean exist;
        try {
            // TODO add your handling code here:
            int existe;
            Boolean existe2=false;
            Manage manager = Manage.getInstance();
            User user = manager.getUser();
            ArrayList<FormForestal> adatosOK=new ArrayList<FormForestal>();
            //ArrayList<FormForestal> sumdatos;
            ArrayList<String> nameAps=new ArrayList<String>();
            ArrayList<String> nameFF=new ArrayList<String>();
            ArrayList<String> errFF=new ArrayList<String>();
            ArrayList errors = new ArrayList();
            Double suma=0.0;
            String[] allkeys=datos.keySet().toArray(new String[0]);
            Hashtable<String, ArrayList<String>> err= new Hashtable<String, ArrayList<String>>();
            for (int i = 0; i < allkeys.length; i++)
            {
                String idapHT=allkeys[i];
                adatosOK=datos.get(idapHT);
                 for (int g = 0; g < adatosOK.size(); g++)
                 {
                    suma=adatosOK.get(g).getValor()+suma;
                 }
                for (int j = 0; j < adatosOK.size(); j++)
                {
                     String select = "select id, id_formforest, anno, area, municipio";
                     String where = "where id='" + idapHT + "' and municipio='" + user.getMunicipio() + "' and  id_formforest='" + adatosOK.get(j).getId() + "' and  anno=" + princ.getSelectedYear() + "";
                     existe = DBAccess.verificarPkey2(select, tablename, where);
                     if (existe != 1) {
                        DBAccess.insertFormacForestal(idapHT, princ.getSelectedYear(),adatosOK.get(j).getId(), adatosOK.get(j).getValor(), tablename);
                     } 
                     else
                     {
                        errors.add(new Integer(j));
                        if(err.size()==0)
                        {
                            errFF.add(adatosOK.get(j).getNombre());
                            err.put(DBAccess.getnameIdentidad(idapHT, "area_protegida"), errFF);
                        }
                        else
                        {
                            exist=err.containsKey(DBAccess.getnameIdentidad(idapHT, "area_protegida"));
                            if(exist)
                            {
                               errFF= err.get(DBAccess.getnameIdentidad(idapHT, "area_protegida"));
                               errFF.add(adatosOK.get(j).getNombre());
                               err.put(DBAccess.getnameIdentidad(idapHT, "area_protegida"), errFF);
                            }
                            else
                            {
                                ArrayList<String> otro=new ArrayList<String>();
                                otro.add(adatosOK.get(j).getNombre());
                                err.put(DBAccess.getnameIdentidad(idapHT, "area_protegida"), otro);
                            }
                        }
                        /*nameAps.add(DBAccess.getnameIdentidad(idapHT, "area_protegida"));
                        nameFF.add(adatosOK.get(j).getNombre()); */
                        continue;
                     }
                }
            }
            if (errors.size() > 0)
            {
                String[] errkeys=err.keySet().toArray(new String[0]);
                
                String tres ="";
            String mfsg="";
            String cuatro="";
            String saltoLine;
            String ap="\n\ren el año "+princ.getSelectedYear()+".";
            //String msgff="En el Área Protegida: '";
                 for (int l = 0; l < errkeys.length; l++)
                {
                   String idaperr=allkeys[l];
                   String nameidaperr= DBAccess.getnameIdentidad(idaperr, "area_protegida");
               String uno="\n\r(*)-En el Área Protegida: '"+nameidaperr+"' ya existe(n) la(s) Formación(es) Forestal(es):\n\r";
               String dos ="";
               for (Integer i =0; i < err.get(nameidaperr).size(); i++)
                {
                    Double multp4=Double.valueOf(i.doubleValue()/4);
                    Integer multp4_I=(int) Math.floor(multp4);//integer
                    Double retornomultp4=multp4-multp4_I;//se resta el decim-integ
                    
                    if(i!=0 && (retornomultp4).equals(0.0))//si el resultado es entero
                    {
                         saltoLine="\n\r";
                         if(i==errors.size()-1)
                         {
                             saltoLine="";
                         }
                    }
                    else
                    {
                        saltoLine="-";
                    }
                    dos = dos+err.get(nameidaperr).get(i)+saltoLine;
                }
               tres=uno+dos+tres;
            }
                JOptionPane.showConfirmDialog(this, tres+ap, "Error!!!", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
            datos.clear();
            ((DefaultListModel)jList_Datos.getModel()).removeAllElements();
            FF.clear();
            ((DefaultListModel)jList_FormFores.getModel()).removeAllElements();
            ShowFF();
            jTextField_Sup.setText("0.0");
        } catch (SQLException ex) {
            Logger.getLogger(Indicador3_1_1.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private String[] getAPnames()
    {
       String namesap[] = new String[idsap.length];
        for (int i = 0; i < idsap.length; i++) {
            try {
                //try {
                namesap[i] = DBAccess.getnameIdentidad(idsap[i][0].toString(), "area_protegida");
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       return namesap;
    }

    private void createFF()
    {
        try {
            String where="where active=true";
            idFF = DBAccess.selectNomenclator("c3_1_1_formacionforestal",where);
            objFF=new FormForestal[idFF.length];
            for (int i = 0; i < idFF.length; i++) {
            objFF[i]=new FormForestal(idFF[i][0].toString(), idFF[i][1].toString(),0.0);
            System.out.println(objFF[i].getNombre());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Indicador3_1_1.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }

    private void ShowFF()
    {
        DefaultListModel modeloFF = new DefaultListModel();
        for (int j = 0; j < objFF.length; j++) {
                modeloFF.addElement(objFF[j].getNombre());
            }
         jList_FormFores.setModel(modeloFF);
        for (int i = 0; i < idsap.length; i++)
        {           
            ArrayList<FormForestal> arrayFF=new ArrayList<FormForestal>();
            for (int j = 0; j < objFF.length; j++) {
                arrayFF.add(objFF[j].Clone());
            }
            FF.put(idsap[i][0].toString(), arrayFF);          
        }
    }

    private void Derecha(int ap,int ff)
    {
        ArrayList<FormForestal> affHT;
        ArrayList<FormForestal> adatosHT;
        affHT=FF.get(idsap[ap][0].toString());
        adatosHT=datos.get(idsap[ap][0].toString());
        if(adatosHT==null)
        {
            adatosHT=new  ArrayList<FormForestal>();
        }
        adatosHT.add(affHT.get(ff));
        datos.put(idsap[ap][0].toString(), adatosHT);
        //eliminar el obj del array del hasT de FF
        affHT.remove(ff);
        //agregar elementos a los modelos de FF y Datos
        ((DefaultListModel)jList_Datos.getModel()).addElement(adatosHT.get(adatosHT.size()-1).getNombre()+" --- Superficie: 0.0");
        ((DefaultListModel)jList_FormFores.getModel()).remove(ff);
        jList_Datos.setSelectedIndex(0);
        if (jList_FormFores.getModel().getSize()>0) {
           jList_FormFores.setSelectedIndex(0);
        }
    }

    private void Izquierda(int ap,int dat)
    {
        ArrayList<FormForestal> aIzdatosHT;
        ArrayList<FormForestal> aIzFFHT;
        FormForestal obj;
        aIzdatosHT=datos.get(idsap[ap][0].toString());
        aIzFFHT=FF.get(idsap[ap][0].toString());
        if(aIzFFHT==null)
        {
            aIzFFHT=new  ArrayList<FormForestal>();
        }
        obj=aIzdatosHT.get(dat);
        obj.setValor(0.0);
        aIzFFHT.add(obj);
        aIzdatosHT.remove(dat);
        if (aIzdatosHT.size()==0) {
            datos.remove(idsap[ap][0].toString());
        }
        ((DefaultListModel)jList_Datos.getModel()).remove(dat);
        ((DefaultListModel)jList_FormFores.getModel()).addElement(aIzFFHT.get(aIzFFHT.size()-1).getNombre());
        jList_FormFores.setSelectedIndex(0);
        if (jList_Datos.getModel().getSize()>0) {
           jList_Datos.setSelectedIndex(0);
        }
         jList_FormFores.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Ok;
    private javax.swing.JButton jButton_flechaAllDer;
    private javax.swing.JButton jButton_flechaAllIzq;
    private javax.swing.JButton jButton_flechaDer;
    private javax.swing.JButton jButton_flechaIzq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList_AreaProt;
    private javax.swing.JList jList_Datos;
    private javax.swing.JList jList_FormFores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_Sup;
    // End of variables declaration//GEN-END:variables

}
