/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador3_1_2.java
 *
 * Created on 27/10/2012, 07:30:22 PM
 */

package cif.gui.Criterio_3;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.manage.Manage;
import cif.manage.User;
import cif.utiles.Adv_ComboBox;
import cif.utiles.EspecieEndm;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador3_1_2_Mod extends javax.swing.JPanel {
    private final String id;
    private final JF_Principal princ;
    private final String tablename;
    private final Object[][] result312;
    private int anno;
    EspecieEndm objEE[];

    /** Creates new form Indicador3_1_2 */
    public Indicador3_1_2_Mod(String id,JF_Principal princ,String tablename,Object[][] result312) {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
        this.result312=result312;
        //initComponents();
        init();
        //******//******************//************//
        anno=princ.getSelectedYear();

        DefaultListModel mdff=new DefaultListModel();
        jListDatos.setModel(mdff);
        createEspEndm();
        ShowEspEndm();
        jListEspEndm.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDatos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEspEndm = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBAsignar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jScrollPane3.setViewportView(jListDatos);

        jListEspEndm.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEspEndmValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEspEndm);

        jLabel2.setText("Especies Endémicas");

        jLabel3.setText("Datos");

        jBAsignar.setText("Asignar");
        jBAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarActionPerformed(evt);
            }
        });

        jLabel4.setText("Programa de Conservación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAsignar)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addComponent(jBAsignar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap())
        );

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(494, Short.MAX_VALUE)
                .addComponent(jBAceptar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDatos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEspEndm = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBAsignar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();
        jComboBox1 = new Adv_ComboBox();
        fillCombobox();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jScrollPane3.setViewportView(jListDatos);

        jListEspEndm.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEspEndmValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEspEndm);

        jLabel2.setText("Especies Endémicas");

        jLabel3.setText("Datos");

        jBAsignar.setText("Asignar");
        jBAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarActionPerformed(evt);
            }
        });

        jLabel4.setText("Programa de Conservación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBAsignar)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAsignar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap())
        );

        jBAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png")));
        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(494, Short.MAX_VALUE)
                .addComponent(jBAceptar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>



    private void jBAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsignarActionPerformed
    String name=jComboBox1.getSelectedItem().toString();
        if (!jListDatos.isSelectionEmpty())
        {
            ((DefaultListModel) jListDatos.getModel()).setElementAt(objEE[jListEspEndm.getSelectedIndex()].getNombre()+ " --- Prog de Conserv: " + name, jListDatos.getSelectedIndex());
            objEE[jListEspEndm.getSelectedIndex()].setValor(java.lang.Integer.parseInt(jComboBox1.getSelectedValue().toString()));
        }
        else
        {
           JOptionPane.showConfirmDialog(this, "Debe seleccionar una Formación \n\r Forestal en la casilla: Datos.", "Atención!!!", JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBAsignarActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:
        int existe;
        Manage manager = Manage.getInstance();
        User user = manager.getUser();
        ArrayList errors = new ArrayList();
        ArrayList<String> nameEE=new ArrayList<String>();
        if(anno==princ.getSelectedYear())
        {
            for (int i = 0; i < objEE.length; i++)
            {
                try {
                    DBAccess.updateEspEndm(id, princ.getSelectedYear(), anno, objEE[i].getId(), objEE[i].getValor(), tablename);
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_2_Mod.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            for (int j = 0; j < objEE.length; j++)
            {
                try {
                    String select = "select id, id_espendm, anno, municipio, progconserv";
                    String where = "where id='" + id + "' and municipio='" + user.getMunicipio() + "' and  id_espendm='" + objEE[j].getId() + "' and  anno=" + princ.getSelectedYear() + "";
                    existe = DBAccess.verificarPkey2(select, tablename, where);
                    if (existe == 1) {
                        errors.add(new Integer(j));
                        nameEE.add(objEE[j].getNombre());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_2_Mod.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (errors.size() > 0)
            {
             String msg ="";
            String mfsg="";
            String saltoLine = null;
            String ap="\n\rpara esta entidad en el año "+princ.getSelectedYear()+".";
            String msgff="Ya existe(n) Especie(s) Endémica(s): \n\r";
            for (Integer i =0; i < errors.size(); i++)
            {
               Double multp4=Double.valueOf(i.doubleValue()/4);
                Integer multp4_I=(int) Math.floor(multp4);//integer
                Double retornomultp4=multp4-multp4_I;//se resta el decim-integ
                if(i!=0 && (retornomultp4).equals(0.0))//si el resultado es entero
                {
                    if(i!=errors.size()-1)
                  {
                      saltoLine="\n\r";
                  }
                  else if(i==errors.size()-1)
                  {
                      saltoLine="";
                  }
                }
                else
                {
                   if(i!=errors.size()-1)
                  {
                      saltoLine="-";
                  }
                  else if(i==errors.size()-1)
                  {
                      saltoLine="";
                  }
                }
                msg = msg+nameEE.get(i)+saltoLine;
            }
                mfsg = msgff+msg+ap;
                JOptionPane.showConfirmDialog(this, mfsg, "Error!!!", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
                for (int j = 0; j < objEE.length; j++)
                {
                    DBAccess.updateEspEndm(id, princ.getSelectedYear(), anno, objEE[j].getId(), objEE[j].getValor(), tablename);
                }
                anno = princ.getSelectedYear();
                JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamnete.", "Confirmación!!!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_2_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jListEspEndmValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEspEndmValueChanged
        try {
            // TODO add your handling code here:
            DefaultListModel modelodatos = new DefaultListModel();
            Integer value = objEE[jListEspEndm.getSelectedIndex()].getValor();
            modelodatos.addElement(objEE[jListEspEndm.getSelectedIndex()].getNombre() + " --- Prog de Conserv: " + DBAccess.getnameIdentidad(java.lang.String.valueOf(value), "si_no"));
            jListDatos.setModel(modelodatos);
            jComboBox1.setSelectedItem(DBAccess.getnameIdentidad(java.lang.String.valueOf(value), "si_no"));
            jListDatos.setSelectedIndex(0);
            } catch (SQLException ex) {
            Logger.getLogger(Indicador3_1_2_Mod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListEspEndmValueChanged

    private void createEspEndm()
    {
            objEE=new EspecieEndm[result312.length];
            for (int i = 0; i <result312.length; i++) {
            try {
                objEE[i] = new EspecieEndm(result312[i][0].toString(), DBAccess.getnameIdentidad(result312[i][0].toString(), "c3_1_2_especendem"), java.lang.Integer.parseInt(result312[i][1].toString()));
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_2_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }

    private void ShowEspEndm()
    {
        DefaultListModel modeloEE = new DefaultListModel();
        for (int j = 0; j < objEE.length; j++) {
            try {
                modeloEE.addElement(DBAccess.getnameIdentidad(result312[j][0].toString(), "c3_1_2_especendem"));
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_2_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
         jListEspEndm.setModel(modeloEE);       
    }

    private void fillCombobox() {
            jComboBox1.removeAllItems();
            Object datos[][];
        try {
                datos = DBAccess.selectNomenclator("si_no","");
                for (int i = 0; i < datos.length; i++) {
                    jComboBox1.addItem(datos[i][0].toString(), datos[i][1].toString());
                }
        } catch (SQLException ex) {
            Logger.getLogger(Indicador3_1_2_Mod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBAsignar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListDatos;
    private javax.swing.JList jListEspEndm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    public Adv_ComboBox jComboBox1;
}
