/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador3_1_4.java
 *
 * Created on 27/10/2012, 08:15:00 PM
 */

package cif.gui.Criterio_3;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.manage.Manage;
import cif.manage.User;
import cif.utiles.ProgramaEduc;
import cif.utiles.utiles;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador3_1_4 extends javax.swing.JPanel {
    private final String id;
    private final JF_Principal princ;
    private final String tablename;
    private final Object[][] result314;
    private Object[][] idact;
    ProgramaEduc objAct[];
    ArrayList<ProgramaEduc> adatos;

    /** Creates new form Indicador3_1_4 */
    public Indicador3_1_4(String id,JF_Principal princ,String tablename,Object[][] result314) {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
        this.result314=result314;
        initComponents();
        adatos=new  ArrayList<ProgramaEduc>();
        DefaultListModel mdact=new DefaultListModel();
        jListDatos.setModel(mdact);
        createActv();
        ShowActv();
        jListActiv.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonDer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDatos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListActiv = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonIzq = new javax.swing.JButton();
        jButtonAllIzq = new javax.swing.JButton();
        jButtonAllDer = new javax.swing.JButton();
        jButtonAsignar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jButtonDer.setText("-->");
        jButtonDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDerActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jListDatos);

        jScrollPane1.setViewportView(jListActiv);

        jLabel2.setText("Actividades");

        jLabel3.setText("Datos");

        jButtonIzq.setText("<--");
        jButtonIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzqActionPerformed(evt);
            }
        });

        jButtonAllIzq.setText("<<--");
        jButtonAllIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllIzqActionPerformed(evt);
            }
        });

        jButtonAllDer.setText("-->>");
        jButtonAllDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllDerActionPerformed(evt);
            }
        });

        jButtonAsignar.setText("Asignar");
        jButtonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de Actividades");

        jTextField1.setText("0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel5.setText("Cantidad de Participantes");

        jTextField2.setText("0");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAllDer, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jButtonDer, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jButtonIzq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jButtonAllIzq, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAsignar)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(199, 199, 199)
                .addComponent(jLabel3)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtonDer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAllDer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIzq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAllIzq)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAsignar)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
        );

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jButtonOK.setText("Aceptar");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(489, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarActionPerformed
        // TODO add your handling code here:
        if (!jListDatos.isSelectionEmpty())
        {
            Integer value=java.lang.Integer.parseInt(jTextField1.getText());
            Integer value1=java.lang.Integer.parseInt(jTextField2.getText());
            adatos.get(jListDatos.getSelectedIndex()).setValor1(value);
            adatos.get(jListDatos.getSelectedIndex()).setValor2(value1);
           ((DefaultListModel)jListDatos.getModel()).setElementAt(adatos.get(jListDatos.getSelectedIndex()).getNombre()+" --- Cant Activ: "+value+" --- Particip: "+value1 ,jListDatos.getSelectedIndex());
            jTextField1.setText("0");
            jTextField2.setText("0");
        }
        else
        {
           JOptionPane.showConfirmDialog(this, "Debe seleccionar la Actividad \n\r en la casilla: Datos.", "Atención!!!", JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAsignarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        utiles.SoloNumberInteger(evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        utiles.SoloNumberInteger(evt);
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButtonDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDerActionPerformed
        // TODO add your handling code here:
        if(jListActiv.isSelectionEmpty())
        {
            return;
        }
        Derecha(jListActiv.getSelectedIndex());
        jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_jButtonDerActionPerformed

    private void jButtonIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzqActionPerformed
        // TODO add your handling code here:
        if (jListDatos.isSelectionEmpty())
        {
            return;
        }
        Izquierda(jListDatos.getSelectedIndex());
    }//GEN-LAST:event_jButtonIzqActionPerformed

    private void jButtonAllIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllIzqActionPerformed
        // TODO add your handling code here:
        while (jListDatos.getModel().getSize()>0) {
        Izquierda(0);
        }
    }//GEN-LAST:event_jButtonAllIzqActionPerformed

    private void jButtonAllDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllDerActionPerformed
        // TODO add your handling code here:
        while (jListActiv.getModel().getSize()>0) {
         jListActiv.setSelectedIndex(0);
         Derecha(0);
        }
    }//GEN-LAST:event_jButtonAllDerActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        int existe;
        Manage manager = Manage.getInstance();
        User user = manager.getUser();
        ArrayList errors = new ArrayList();
        ArrayList<String> nameAct=new ArrayList<String>();
                for (int i = 0; i < adatos.size(); i++)
                {
                try {
                    String select = "select id, id_ejeceduc, anno,  municipio";
                    String where = "where id='" + id + "' and municipio='" + user.getMunicipio() + "' and  id_ejeceduc='" + adatos.get(i).getId() + "' and  anno=" + princ.getSelectedYear() + " ";
                    existe = DBAccess.verificarPkey2(select, tablename, where);
                    if (existe != 1) {
                        DBAccess.insertProgEducExt(id, princ.getSelectedYear(), adatos.get(i).getId(),adatos.get(i).getValor1(),adatos.get(i).getValor2(), tablename);
                    } else {
                        errors.add(new Integer(i));
                        nameAct.add(DBAccess.getnameIdentidad(adatos.get(i).getId(), "c3_1_4_progeducext"));
                        continue;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_2.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
        if (errors.size() > 0)
            {
            String msg ="";
            String mfsg="";
            String saltoLine = null;
            String ap="\n\rpara esta entidad en el año "+princ.getSelectedYear()+".";
            String msgff="Ya existe(n) el(los) Programa(s) de Educación y Extención: \n\r";
            for (Integer i =0; i < errors.size(); i++)
            {
               Double multp4=Double.valueOf(i.doubleValue()/4);
                Integer multp4_I=(int) Math.floor(multp4);//integer
                Double retornomultp4=multp4-multp4_I;//se resta el decim-integ
                if(i!=0 && (retornomultp4).equals(0.0))//si el resultado es entero
                {
                  if(i!=errors.size()-1)
                  {
                      saltoLine="\n\r";
                  }
                  else if(i==errors.size()-1)
                  {
                      saltoLine="";
                  }
                }
                else
                {
                    if(i!=errors.size()-1)
                  {
                      saltoLine="-";
                  }
                  else if(i==errors.size()-1)
                  {
                      saltoLine="";
                  }
                }
                msg = msg+nameAct.get(i)+saltoLine;
            }
                mfsg = msgff+msg+ap;
                JOptionPane.showConfirmDialog(this, mfsg, "Error!!!", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
            adatos.clear();
            ((DefaultListModel)jListDatos.getModel()).removeAllElements();
            ((DefaultListModel)jListActiv.getModel()).removeAllElements();
            ShowActv();
            jTextField1.setText("0");
            jTextField2.setText("0");
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void createActv()
    {
        try {
            String where="where active=true";
            idact = DBAccess.selectNomenclator("c3_1_4_progeducext",where);
            objAct=new ProgramaEduc[idact.length];
            for (int i = 0; i < idact.length; i++) {
            objAct[i]=new ProgramaEduc(idact[i][0].toString(), idact[i][1].toString(),0,0);
            System.out.println(objAct[i].getNombre());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Indicador3_1_4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ShowActv()
    {
        DefaultListModel modeloAct = new DefaultListModel();
        for (int j = 0; j < objAct.length; j++) {
                modeloAct.addElement(objAct[j]);
            }
         jListActiv.setModel(modeloAct);
    }

    private void Derecha(int index)
    {
        DefaultListModel dmAct=(DefaultListModel) jListActiv.getModel();
        ProgramaEduc elemAct=(ProgramaEduc) dmAct.get(index);
        adatos.add(elemAct);
        ((DefaultListModel)jListDatos.getModel()).addElement(elemAct.getNombre()+" --- Cant Actv: 0 --- Particp: 0");
        dmAct.remove(index);
        if (jListActiv.getModel().getSize()>0) {
           jListActiv.setSelectedIndex(0);
        }
        jListDatos.setSelectedIndex(0);
    }

    private void Izquierda(int index)
    {
        DefaultListModel dfmAct=(DefaultListModel) jListActiv.getModel();
        dfmAct.addElement(adatos.get(index));
        adatos.remove(index);
        ((DefaultListModel) jListDatos.getModel()).remove(index);
        if (jListDatos.getModel().getSize()>0) {
           jListDatos.setSelectedIndex(0);
        }
        jListActiv.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAllDer;
    private javax.swing.JButton jButtonAllIzq;
    private javax.swing.JButton jButtonAsignar;
    private javax.swing.JButton jButtonDer;
    private javax.swing.JButton jButtonIzq;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListActiv;
    private javax.swing.JList jListDatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
