/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador3_1_3.java
 *
 * Created on 27/10/2012, 07:56:17 PM
 */

package cif.gui.Criterio_3;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.manage.Manage;
import cif.manage.User;
import cif.utiles.ProgramaProtec;
import cif.utiles.utiles;
import java.awt.Container;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador3_1_3_Mod extends javax.swing.JPanel {

private final String id;
    private final JF_Principal princ;
    private final String tablename;
    private final Object[][] result313;
    private int anno;
    ProgramaProtec objPP[];
    /** Creates new form Indicador3_1_3 */
    public Indicador3_1_3_Mod(String id,JF_Principal princ,String tablename,Object[][] result313) {
        this.id=id;
        this.princ=princ;
        this.tablename=tablename;
        this.result313=result313;
        initComponents();
        //******//******************//************//
        anno=princ.getSelectedYear();
        DefaultListModel mdpp=new DefaultListModel();
        jList_Datos.setModel(mdpp);
        createProgama();
        ShowProgama();
        jList_Prog.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Datos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Prog = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAsignar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jScrollPane3.setViewportView(jList_Datos);

        jList_Prog.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ProgValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Prog);

        jLabel2.setText("Programas de Protección");

        jLabel3.setText("Datos");

        jButtonAsignar.setText("Asignar");
        jButtonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarActionPerformed(evt);
            }
        });

        jLabel4.setText("Superficie(ha):");

        jTextField1.setText("0.0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAsignar)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAsignar)))
                .addContainerGap())
        );

        jButtonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jButtonOk.setText("Aceptar");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarActionPerformed
        String name=jTextField1.getText();
        if (!jList_Datos.isSelectionEmpty())
        {
            ((DefaultListModel) jList_Datos.getModel()).setElementAt(objPP[jList_Prog.getSelectedIndex()].getNombre()+ " --- Prog de Conserv: " + name, jList_Datos.getSelectedIndex());
            objPP[jList_Prog.getSelectedIndex()].setValor(java.lang.Double.parseDouble(name));
        }
        else
        {
           JOptionPane.showConfirmDialog(this, "Debe seleccionar un Programa \n\r de Protección en la casilla: Datos.", "Atención!!!", JOptionPane.CLOSED_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAsignarActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        int existe;
        Manage manager = Manage.getInstance();
        User user = manager.getUser();
        ArrayList errors = new ArrayList();
        ArrayList<String> namePP=new ArrayList<String>();
        if(anno==princ.getSelectedYear())
        {
            for (int i = 0; i < objPP.length; i++)
            {
                try {
                    DBAccess.updateEjecProgProtec(id, princ.getSelectedYear(), anno, objPP[i].getId(), objPP[i].getValor(), tablename);
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_3_Mod.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            for (int j = 0; j < objPP.length; j++)
            {
                try {
                    String select = "select id, id_ejecprgm, anno, municipio, superficie";
                    String where = "where id='" + id + "' and municipio='" + user.getMunicipio() + "' and  id_ejecprgm='" + objPP[j].getId() + "' and  anno=" + princ.getSelectedYear() + "";
                    existe = DBAccess.verificarPkey2(select, tablename, where);
                    if (existe == 1) {
                        errors.add(new Integer(j));
                        namePP.add(objPP[j].getNombre());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Indicador3_1_3_Mod.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (errors.size() > 0)
            {
                String msg ="";
                String mfsg="";
                String saltoLine = null;
                String ap="\n\rpara esta entidad en el año "+princ.getSelectedYear()+".";
                String msgff="Ya existe(n) el(los) Programa(s) de Protección: \n\r";
                for (Integer i =0; i < errors.size(); i++)
                {
                   Double multp4=Double.valueOf(i.doubleValue()/4);
                    Integer multp4_I=(int) Math.floor(multp4);//integer
                    Double retornomultp4=multp4-multp4_I;//se resta el decim-integ
                    if(i!=0 && (retornomultp4).equals(0.0))//si el resultado es entero
                    {
                        if(i!=errors.size()-1)
                        {
                            saltoLine="\n\r";
                        }
                        else if(i==errors.size()-1)
                        {
                            saltoLine="";
                        }
                    }
                    else
                    {
                       if(i!=errors.size()-1)
                        {
                            saltoLine="-";
                        }
                        else if(i==errors.size()-1)
                        {
                            saltoLine="";
                        }
                    }
                    msg = msg+namePP.get(i)+saltoLine;
                }
                    mfsg = msgff+msg+ap;
                    JOptionPane.showConfirmDialog(this, mfsg, "Error!!!", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        else
        {
            try {
                for (int j = 0; j < objPP.length; j++)
                {
                    DBAccess.updateEjecProgProtec(id, princ.getSelectedYear(), anno, objPP[j].getId(), objPP[j].getValor(), tablename);
                }
                anno = princ.getSelectedYear();
                JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamente.", "Confirmación!!!", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_3_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jList_ProgValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ProgValueChanged
            DefaultListModel modelodatos = new DefaultListModel();
            Double value = objPP[jList_Prog.getSelectedIndex()].getValor();
            modelodatos.addElement(objPP[jList_Prog.getSelectedIndex()].getNombre() + " --- Prog de Conserv: " + value);
            jList_Datos.setModel(modelodatos);
            jList_Datos.setSelectedIndex(0);
            jTextField1.setText(value.toString());
    }//GEN-LAST:event_jList_ProgValueChanged

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if(evt.getAncestorParent() instanceof Container)
        {
            jTextField1.requestFocusInWindow();
        }
    }//GEN-LAST:event_formAncestorAdded


    private void createProgama()
    {
      objPP=new ProgramaProtec[result313.length];
            for (int i = 0; i <result313.length; i++) {
            try {
                objPP[i] = new ProgramaProtec(result313[i][0].toString(), DBAccess.getnameIdentidad(result313[i][0].toString(), "c3_1_3_ejecprogprotec"), java.lang.Double.parseDouble(result313[i][1].toString()));
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_3_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }

    private void ShowProgama()
    {
        DefaultListModel modeloPP = new DefaultListModel();
        for (int j = 0; j < objPP.length; j++) {
            try {
                modeloPP.addElement(DBAccess.getnameIdentidad(result313[j][0].toString(), "c3_1_3_ejecprogprotec"));
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_1_3_Mod.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
         jList_Prog.setModel(modeloPP);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList_Datos;
    private javax.swing.JList jList_Prog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
