/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Indicador3_2_3.java
 *
 * Created on 27/10/2012, 08:34:11 PM
 */

package cif.gui.Criterio_3;

import cif.bd.DBAccess;
import cif.gui.JF_Principal;
import cif.utiles.utiles;
import java.awt.Container;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class Indicador3_2_3 extends javax.swing.JPanel {
    private final String id;
    private final String tablename;
    private final String tag;
    private final Object[][] result323;
    JF_Principal princ;
    private  int anno;

    /** Creates new form Indicador3_2_3 */
    public Indicador3_2_3(String id,JF_Principal princ,String tablename,String tag,Object[][] result323) {
        this.id=id;
        this.tablename=tablename;
        this.tag=tag;
        this.result323=result323;
         this.princ=princ;
        initComponents();
        anno=princ.getSelectedYear();
        if (tag.equals("modify")) {
            this.jTextField_Lprinc.setText(result323[0][0].toString());
            this.jTextField_ARFprinc.setText(result323[0][1].toString());
            this.jTextField_Lprimer.setText(result323[0][2].toString());
            this.jTextField_ARFprimer.setText(result323[0][3].toString());
            this.jTextField_Lseg.setText(result323[0][4].toString());
            this.jTextField_ARFseg.setText(result323[0][5].toString());
            this.jTextField_STZP.setText(result323[0][6].toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Aceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Lprinc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_STZP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Lprimer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Lseg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_ARFprinc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_ARFprimer = new javax.swing.JTextField();
        jTextField_ARFseg = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-accept.png"))); // NOI18N
        jButton_Aceptar.setText("Aceptar");
        jButton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del indicador"));

        jLabel2.setText("Longitud  principales(m):");

        jLabel3.setText("Ancho real faja segundo orden(m):");

        jTextField_Lprinc.setText("0.0");
        jTextField_Lprinc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LprincKeyTyped(evt);
            }
        });

        jLabel4.setText("Superficie total zona protección(ha):");

        jTextField_STZP.setText("0.0");
        jTextField_STZP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_STZPKeyTyped(evt);
            }
        });

        jLabel5.setText("Longitud  primer orden(m):");

        jTextField_Lprimer.setText("0.0");
        jTextField_Lprimer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LprimerKeyTyped(evt);
            }
        });

        jLabel6.setText("Longitud  segundo orden(m):");

        jTextField_Lseg.setText("0.0");
        jTextField_Lseg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LsegKeyTyped(evt);
            }
        });

        jLabel7.setText("Ancho real faja principales(m):");

        jTextField_ARFprinc.setText("0.0");
        jTextField_ARFprinc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ARFprincKeyTyped(evt);
            }
        });

        jLabel8.setText("Ancho real faja primer orden(m):");

        jTextField_ARFprimer.setText("0.0");
        jTextField_ARFprimer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ARFprimerKeyTyped(evt);
            }
        });

        jTextField_ARFseg.setText("0.0");
        jTextField_ARFseg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ARFsegKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ARFprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Lseg, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_ARFseg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jTextField_Lprimer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jTextField_ARFprinc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jTextField_Lprinc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_STZP, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Lprinc))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_ARFprinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_Lprimer))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ARFprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Lseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ARFseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_STZP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Aceptar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Aceptar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarActionPerformed
        // TODO add your handling code here:
        Double longprinc=java.lang.Double.parseDouble(jTextField_Lprinc.getText());
        Double arfprinc=java.lang.Double.parseDouble(jTextField_ARFprinc.getText());
        Double long1er=java.lang.Double.parseDouble(jTextField_Lprimer.getText());
        Double arf1er=java.lang.Double.parseDouble(jTextField_ARFprimer.getText());
        Double long2do=java.lang.Double.parseDouble(jTextField_Lseg.getText());
        Double arf2do=java.lang.Double.parseDouble(jTextField_ARFseg.getText());
        Double stzprot=java.lang.Double.parseDouble(jTextField_STZP.getText());
        int existe;
        try {
            if (tag.equals("insert")) {
                 existe=DBAccess.verificarPkey(id, princ.getSelectedYear(), tablename);
                if(existe!=1)
                {
                    DBAccess.insertCorrFluvial(id,princ.getSelectedYear(),longprinc,arfprinc,long1er,arf1er,long2do,arf2do,stzprot,tablename);
                    jTextField_Lprinc.setText("0.0");
                    jTextField_ARFprinc.setText("0.0");
                    jTextField_Lprimer.setText("0.0");
                    jTextField_ARFprimer.setText("0.0");
                    jTextField_Lseg.setText("0.0");
                    jTextField_ARFseg.setText("0.0");
                    jTextField_STZP.setText("0.0");
                }
                else
                {
                    JOptionPane.showConfirmDialog(this, "Ya existen datos para esta entidad en el año "+princ.getSelectedYear()+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
                }
            } else if (tag.equals("modify")) {
                if(anno==princ.getSelectedYear())
                {
                    DBAccess.updateCorrFluvial(id,princ.getSelectedYear(),anno,longprinc,arfprinc,long1er,arf1er,long2do,arf2do,stzprot,tablename);
                    JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamente.", "Confirmación!!!", JOptionPane.CLOSED_OPTION,JOptionPane.INFORMATION_MESSAGE);
                    anno=princ.getSelectedYear();
                }
                else
                {
                    existe=DBAccess.verificarPkey(id, princ.getSelectedYear(), tablename);
                    if(existe!=1)
                    {
                        DBAccess.updateCorrFluvial(id,princ.getSelectedYear(),anno,longprinc,arfprinc,long1er,arf1er,long2do,arf2do,stzprot,tablename);
                        JOptionPane.showConfirmDialog(this, "Los datos han sido guardados satisfactoriamente.", "Confirmación!!!", JOptionPane.CLOSED_OPTION,JOptionPane.INFORMATION_MESSAGE);
                        anno=princ.getSelectedYear();
                    }
                    else
                    {
                        JOptionPane.showConfirmDialog(this, "Ya existen datos para esta entidad en el año "+princ.getSelectedYear()+".", "Error!!!", JOptionPane.CLOSED_OPTION,JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(Indicador3_2_3.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton_AceptarActionPerformed

    private void jTextField_LprincKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LprincKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_Lprinc.getText());
    }//GEN-LAST:event_jTextField_LprincKeyTyped

    private void jTextField_ARFprincKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ARFprincKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_ARFprinc.getText());
    }//GEN-LAST:event_jTextField_ARFprincKeyTyped

    private void jTextField_LprimerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LprimerKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_Lprimer.getText());
    }//GEN-LAST:event_jTextField_LprimerKeyTyped

    private void jTextField_ARFprimerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ARFprimerKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_ARFprimer.getText());
    }//GEN-LAST:event_jTextField_ARFprimerKeyTyped

    private void jTextField_LsegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LsegKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_Lseg.getText());
    }//GEN-LAST:event_jTextField_LsegKeyTyped

    private void jTextField_ARFsegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ARFsegKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_ARFseg.getText());
    }//GEN-LAST:event_jTextField_ARFsegKeyTyped

    private void jTextField_STZPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_STZPKeyTyped
        // TODO add your handling code here:
        utiles.SoloNumber(evt,jTextField_STZP.getText());
    }//GEN-LAST:event_jTextField_STZPKeyTyped

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if(evt.getAncestorParent() instanceof Container)
        {
            jTextField_Lprinc.requestFocusInWindow();
        }
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Aceptar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField_ARFprimer;
    public javax.swing.JTextField jTextField_ARFprinc;
    public javax.swing.JTextField jTextField_ARFseg;
    public javax.swing.JTextField jTextField_Lprimer;
    public javax.swing.JTextField jTextField_Lprinc;
    public javax.swing.JTextField jTextField_Lseg;
    public javax.swing.JTextField jTextField_STZP;
    // End of variables declaration//GEN-END:variables

}
